<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SystemDefinition [
 <!ELEMENT SystemDefinition ( systemModel?, SystemBuild? )>
 <!ATTLIST SystemDefinition
  name CDATA #REQUIRED
  schema CDATA #REQUIRED>
 <!ELEMENT systemModel (layer+)>
 <!ELEMENT layer (block* | collection*)*>
 <!ATTLIST layer
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED>
 <!ELEMENT block (subblock* | collection*)*>
 <!ATTLIST block
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED
  level NMTOKEN #IMPLIED
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED>
 <!ELEMENT subblock (collection)*>
 <!ATTLIST subblock
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED>
 <!ELEMENT collection (component)*>
 <!ATTLIST collection
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  level NMTOKEN #IMPLIED>
 <!ELEMENT component (unit)*>
 <!ATTLIST component
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  deprecated CDATA #IMPLIED
  introduced CDATA #IMPLIED
  contract CDATA #IMPLIED
  plugin (Y|N) "N"
  filter CDATA #IMPLIED
  class NMTOKENS #IMPLIED
  supports CDATA #IMPLIED>
 <!ELEMENT unit EMPTY>
 <!ATTLIST unit
  mrp CDATA #IMPLIED
  filter CDATA #IMPLIED
  bldFile CDATA #IMPLIED
  root CDATA #IMPLIED
  version NMTOKEN #IMPLIED
  prebuilt NMTOKEN #IMPLIED
  late (Y|N) #IMPLIED
  priority CDATA #IMPLIED>
 <!ELEMENT SystemBuild (option* | target+ | targetList+ | list+ | configuration+)*>
 <!ATTLIST SystemBuild schema CDATA #REQUIRED>
 <!ELEMENT list (ref+)>
 <!ATTLIST list
  name ID #REQUIRED
  description CDATA #REQUIRED>
 <!ELEMENT ref EMPTY>
 <!ATTLIST ref item CDATA #REQUIRED>
 <!ELEMENT targetList EMPTY>
 <!ATTLIST targetList
  name ID #REQUIRED
  description CDATA #REQUIRED
  target IDREFS #REQUIRED>
 <!ELEMENT target EMPTY>
 <!ATTLIST target
  name ID #REQUIRED
  abldTarget CDATA #REQUIRED
  description CDATA #REQUIRED>
 <!ELEMENT option EMPTY>
 <!ATTLIST option
  name ID #REQUIRED
  abldOption CDATA #REQUIRED
  description CDATA #REQUIRED
  enable (Y | N ) #REQUIRED>
 <!ELEMENT configuration (listRef+ | ref+ | task+)*>
 <!ATTLIST configuration
  name ID #REQUIRED
  description CDATA #REQUIRED
  filter CDATA #REQUIRED>
 <!ELEMENT task (listRef* , (buildLayer | specialInstructions))>
 <!ELEMENT listRef EMPTY>
 <!ATTLIST listRef list CDATA #REQUIRED>
 <!ELEMENT buildLayer EMPTY>
 <!ATTLIST buildLayer
  command CDATA #REQUIRED
  targetList IDREFS #IMPLIED
  unitParallel (Y | N ) #REQUIRED
  targetParallel (Y | N ) "N">
 <!ELEMENT specialInstructions EMPTY>
 <!ATTLIST specialInstructions
  name CDATA #REQUIRED
  cwd CDATA #REQUIRED
  root CDATA #IMPLIED
  command CDATA #REQUIRED>
]>
<SystemDefinition name="Symbian" schema="2.0.1">
 <systemModel>
  <layer name="os" long-name="OS" levels="hw services">
   <block name="kernelhwsrv" long-name="Kernel and Hardware Services" level="hw" levels="hw-if adaptation framework test">
    <collection name="baseintegtests" long-name="Base Integration Testing" level="test">
     <component name="baseintegrationtest" long-name="Base Integration Test" introduced="9.3">
      <unit bldFile="os\kernelhwsrv\baseintegtests\baseintegrationtest\group" mrp="os\kernelhwsrv\baseintegtests\baseintegrationtest\group\base_integration_test.mrp"/>
     </component>
    </collection>
    <collection name="brdbootldr" long-name="Board Boot Loader" level="hw-if">
     <component name="ubootldr" long-name="Boot Loader" introduced="9.2">
      <unit mrp="os\kernelhwsrv\brdbootldr\ubootldr\base_ubootldr.mrp"/>
     </component>
    </collection>
    <collection name="unistore2" long-name="UniStore2 Flash Translation Layer" level="hw-if">
     <component name="uiidrivers" long-name="UniStore2 Drivers" filter="gt" introduced="9.1">
      <unit bldFile="os\kernelhwsrv\kernel\eka\drivers\unistore2" mrp="os\kernelhwsrv\kernel\eka\drivers\unistore2\base_drivers_unistore2.mrp"/>
     </component>
     <component name="uiicore" long-name="UniStore2 Core" filter="gt" introduced="9.1">
      <unit mrp="os\kernelhwsrv\kernel\eka\drivers\unistore2\base_drivers_unistore2_undeliverable.mrp"/>
     </component>
     <component name="uiicrashlogger" long-name="UniStore2 Crash Logger" filter="gt" introduced="9.1">
      <unit bldFile="os\kernelhwsrv\kernel\eka\drivers\crashflash\unistore2" mrp="os\kernelhwsrv\kernel\eka\drivers\crashflash\unistore2\base_crashflash_unistore2.mrp"/>
     </component>
     <component name="uiibootsupport" long-name="UniStore2 Boot Support" filter="gt" introduced="9.1">
      <unit bldFile="os\kernelhwsrv\unistore2\uiibootsupport\nandloader\unistore2" mrp="os\kernelhwsrv\unistore2\uiibootsupport\base_nandboot_unistore2.mrp"/>
     </component>
    </collection>
    <collection name="bsptemplate" long-name="BSP Template" level="hw-if">
     <component name="asspandvariant" long-name="Template ASSP and Variant" introduced="6.0">
      <unit bldFile="os\kernelhwsrv\bsptemplate\asspandvariant\template_variant" mrp="os\kernelhwsrv\bsptemplate\asspandvariant\base_template.mrp"/>
     </component>
    </collection>
    <collection name="kernel" long-name="Kernel Architecture" level="adaptation">
     <component name="eka" long-name="Kernel Architecture" introduced="8.0">
      <unit bldFile="os\kernelhwsrv\kernel\eka" mrp="os\kernelhwsrv\kernel\eka\base_e32.mrp"/>
     </component>
    </collection>
    <collection name="kerneltest" long-name="Kernel Test" level="hw-if">
     <component name="e32test" long-name="E32 Tests" class="test">
      <unit bldFile="os\kernelhwsrv\kerneltest\e32test\group" mrp="os\kernelhwsrv\kerneltest\e32test\group\base_e32test.mrp"/>
     </component>
     <component name="sdiotest" long-name="SDIO Tests" filter="gt" introduced="9.2" class="test">
      <unit bldFile="os\kernelhwsrv\kerneltest\sdiotest" mrp="os\kernelhwsrv\kerneltest\sdiotest\base_sdiotests.mrp"/>
     </component>
     <component name="e32utils" long-name="E32 Utilities">
      <unit bldFile="os\kernelhwsrv\kerneltest\e32utils\group" mrp="os\kernelhwsrv\kerneltest\e32utils\group\base_e32utils.mrp"/>
     </component>
     <component name="f32test" long-name="File Server Tests" class="test">
      <unit bldFile="os\kernelhwsrv\kerneltest\f32test\group" mrp="os\kernelhwsrv\kerneltest\f32test\group\base_f32test.mrp"/>
     </component>
    </collection>
    <collection name="ldds" long-name="Logical Device Drivers" level="adaptation">
     <component name="ethernetldd" long-name="Ethernet Drivers">
      <unit bldFile="os\kernelhwsrv\kernel\eka\drivers\ethernet" mrp="os\kernelhwsrv\kernel\eka\drivers\ethernet\base_e32_drivers_ethernet.mrp"/>
     </component>
     <component name="audioldd" long-name="Audio Drivers" introduced="8.1b">
      <unit bldFile="os\kernelhwsrv\kernel\eka\drivers\esound" mrp="os\kernelhwsrv\kernel\eka\drivers\esound\base_e32_drivers_sound.mrp"/>
     </component>
     <component name="serialldd" long-name="Serial Port Drivers">
      <unit bldFile="os\kernelhwsrv\kernel\eka\drivers\ecomm" mrp="os\kernelhwsrv\kernel\eka\drivers\ecomm\base_e32_drivers_ecomm.mrp"/>
     </component>
     <component name="legacydrivers" long-name="Legacy Drivers">
      <unit mrp="os\kernelhwsrv\kernel\eka\drivers\adc\base_e32_drivers_adc.mrp"/>
     </component>
     <component name="locmedia" long-name="Local Media Subsystem" introduced="8.1b">
      <!-- these are LDDs for storage media-->
      <unit bldFile="os\kernelhwsrv\kernel\eka\drivers\locmedia" mrp="os\kernelhwsrv\kernel\eka\drivers\locmedia\base_e32_drivers_locmedia.mrp"/>
     </component>
     <component name="runmodedebugger" long-name="Run Mode Debugger">
      <unit bldFile="os\kernelhwsrv\kernel\eka\drivers\debug" mrp="os\kernelhwsrv\kernel\eka\drivers\debug\base_e32_drivers_debug.mrp"/>
     </component>
     <component name="btrace" long-name="Kernel Trace Tool">
      <unit bldFile="os\kernelhwsrv\kernel\eka\drivers\trace" mrp="os\kernelhwsrv\kernel\eka\drivers\trace\base_e32_drivers_trace.mrp"/>
     </component>
    </collection>
    <collection name="driversupport" long-name="Generic Driver Support" level="hw-if">
     <component name="sdcard3c" long-name="SD Card 3C Driver" filter="gt" introduced="9.1">
      <unit bldFile="os\kernelhwsrv\kernel\eka\drivers\pbus\mmc\sdcard\sdcard3c" mrp="os\kernelhwsrv\kernel\eka\drivers\pbus\mmc\sdcard\sdcard3c\base_e32_sd3c.mrp"/>
     </component>
     <component name="sdcard4c" long-name="SD Card 4C Driver" filter="gt" introduced="9.1">
      <unit bldFile="os\kernelhwsrv\kernel\eka\drivers\pbus\mmc\sdcard\sdcard4c" mrp="os\kernelhwsrv\kernel\eka\drivers\pbus\mmc\sdcard\sdcard4c\base_e32_sd4c.mrp"/>
     </component>
     <component name="mediadrivers" long-name="Media Drivers">
      <!-- these are for storage media-->
      <unit bldFile="os\kernelhwsrv\kernel\eka\drivers\media" mrp="os\kernelhwsrv\kernel\eka\drivers\media\base_e32_drivers_media.mrp"/>
     </component>
     <component name="genericboardsupport" long-name="Generic Board Support">
      <unit bldFile="os\kernelhwsrv\kernel\eka\drivers\bsp" mrp="os\kernelhwsrv\kernel\eka\drivers\bsp\base_e32_drivers_bsp.mrp"/>
     </component>
    </collection>
    <collection name="localisation" long-name="Localisation" level="adaptation">
     <component name="localesupport" long-name="Locale Support" plugin="Y">
      <unit bldFile="os\kernelhwsrv\localisation\localesupport" mrp="os\kernelhwsrv\localisation\localesupport\mmpfiles\base_loce32.mrp"/>
     </component>
    </collection>
    <collection name="userlibandfileserver" long-name="User Library and File Server" level="framework">
     <component name="euser" long-name="User Library">
      <unit bldFile="os\kernelhwsrv\kernel\eka\euser" mrp="os\kernelhwsrv\kernel\eka\euser\base_e32_euser.mrp"/>
     </component>
     <component name="compsupp" long-name="Compiler Runtime Support" filter="gt">
      <unit bldFile="os\kernelhwsrv\kernel\eka\compsupp" mrp="os\kernelhwsrv\kernel\eka\compsupp\base_e32_compsupp.mrp"/>
     </component>
     <component name="fileserver" long-name="File Server" filter="gt">
      <unit bldFile="os\kernelhwsrv\userlibandfileserver\fileserver\group" mrp="os\kernelhwsrv\userlibandfileserver\fileserver\group\base_f32.mrp"/>
     </component>
     <component name="fatfilenameconversionplugins" long-name="FAT Filename Conversion Plugins" plugin="Y" introduced="9.1">
      <unit bldFile="os\kernelhwsrv\userlibandfileserver\fatfilenameconversionplugins\group" mrp="os\kernelhwsrv\userlibandfileserver\fatfilenameconversionplugins\group\syslibs_FATCharsetConv.mrp"/>
     </component>
     <component name="nandftl" long-name="SSR Flash Translation Layer" filter="gt" introduced="7.0s" deprecated="9.1">
      <unit bldFile="os\kernelhwsrv\userlibandfileserver\fileserver\sftl" mrp="os\kernelhwsrv\userlibandfileserver\fileserver\sftl\base_f32_sftl.mrp"/>
     </component>
     <component name="estart" long-name="Base Starter" filter="gt">
      <unit bldFile="os\kernelhwsrv\userlibandfileserver\fileserver\estart" mrp="os\kernelhwsrv\userlibandfileserver\fileserver\estart\base_f32_estart.mrp"/>
     </component>
     <component name="domainmgr" long-name="Domain Manager" introduced="8.1b">
      <unit bldFile="os\kernelhwsrv\userlibandfileserver\domainmgr\group" mrp="os\kernelhwsrv\userlibandfileserver\domainmgr\group\base_domain.mrp"/>
     </component>
     <component name="basedocs" long-name="Base Documentation">
      <unit mrp="os\kernelhwsrv\userlibandfileserver\basedocs\base_documentation.mrp"/>
     </component>
    </collection>
    <collection name="filesystems" long-name="File Systems" level="framework">
     <component name="romfs" long-name="ROM File System" filter="gt" plugin="Y">
      <unit mrp="os\kernelhwsrv\userlibandfileserver\fileserver\srom\base_f32_srom.mrp"/>
     </component>
     <component name="rofs" long-name="ROFS" filter="gt" plugin="Y">
      <unit bldFile="os\kernelhwsrv\userlibandfileserver\fileserver\srofs" mrp="os\kernelhwsrv\userlibandfileserver\fileserver\srofs\base_f32_srofs.mrp"/>
     </component>
     <component name="usbmsfs" long-name="USB Mass Storage File System" filter="gt" plugin="Y">
      <unit bldFile="os\kernelhwsrv\userlibandfileserver\fileserver\smassstorage" mrp="os\kernelhwsrv\userlibandfileserver\fileserver\smassstorage\base_f32_smassstorage.mrp"/>
     </component>
     <component name="fat32fs" long-name="FAT32 File System" filter="gt" plugin="Y">
      <unit bldFile="os\kernelhwsrv\userlibandfileserver\fileserver\sfat32" mrp="os\kernelhwsrv\userlibandfileserver\fileserver\sfat32\base_f32_sfat32.mrp"/>
     </component>
     <component name="fatfs" long-name="FAT File System" filter="gt" plugin="Y">
      <unit bldFile="os\kernelhwsrv\userlibandfileserver\fileserver\sfat" mrp="os\kernelhwsrv\userlibandfileserver\fileserver\sfat\base_f32_sfat.mrp"/>
     </component>
     <component name="compfs" long-name="Composite File System" filter="gt" plugin="Y">
      <unit bldFile="os\kernelhwsrv\userlibandfileserver\fileserver\scomp" mrp="os\kernelhwsrv\userlibandfileserver\fileserver\scomp\base_f32_scomp.mrp"/>
     </component>
     <component name="ntfs" long-name="NTFS" filter="gt" plugin="Y">
      <unit bldFile="os\kernelhwsrv\userlibandfileserver\fileserver\ntfs" mrp="os\kernelhwsrv\userlibandfileserver\fileserver\ntfs\base_f32_sntfs.mrp"/>
     </component>
     <component name="iso9660fs" long-name="ISO9660 File System" filter="gt" plugin="Y" introduced="8.1b">
      <unit bldFile="os\kernelhwsrv\userlibandfileserver\fileserver\iso9660" mrp="os\kernelhwsrv\userlibandfileserver\fileserver\iso9660\base_f32_siso9660.mrp"/>
     </component>
    </collection>
    <collection name="halservices" long-name="HAL Services" level="framework">
     <component name="hal" long-name="User-Side Hardware Abstraction" introduced="6.0">
      <unit bldFile="os\kernelhwsrv\halservices\hal" mrp="os\kernelhwsrv\halservices\hal\base_hal.mrp"/>
     </component>
    </collection>
    <collection name="textmodeshell" long-name="Text Mode Shell" level="test">
     <component name="e32wsrv" long-name="Text Window Server">
      <unit bldFile="os\kernelhwsrv\kernel\eka\ewsrv" mrp="os\kernelhwsrv\kernel\eka\ewsrv\base_e32_ewsrv.mrp"/>
     </component>
     <component name="textshell" long-name="Text Shell" filter="gt">
      <unit bldFile="os\kernelhwsrv\userlibandfileserver\fileserver\etshell" mrp="os\kernelhwsrv\userlibandfileserver\fileserver\etshell\base_f32_eshell.mrp"/>
     </component>
    </collection>
    <collection name="baseapitest" long-name="Base API Tests" level="test">
     <component name="basesvs" long-name="Base Verification Suite" class="placeholder test" introduced="tb91">
      <!-- PLACEHOLDER="DS.1603"
			<unit mrp="os/kernelhwsrv/baseapitest/group/basesvs.mrp"/>
			-->
     </component>
    </collection>
   </block>
   <block name="boardsupport" long-name="Board Support" level="hw" levels="bsp test 2 3 4">
    <collection name="emulator" long-name="Emulator" level="bsp">
     <component name="emulatorbsp" long-name="Emulator BSP">
      <unit bldFile="os\boardsupport\emulator\emulatorbsp" mrp="os\boardsupport\emulator\emulatorbsp\base_wins.mrp"/>
     </component>
     <component name="unistore2emulatorsupport" long-name="UniStore2 Emulator Support" filter="gt" introduced="tb91">
      <unit bldFile="os\boardsupport\emulator\unistore2emulatorsupport" mrp="os\boardsupport\emulator\unistore2emulatorsupport\base_wins_unistore2.mrp"/>
     </component>
    </collection>
    <collection name="omaph2" long-name="OMAP H2" level="bsp">
     <component name="omaph2bsp" long-name="OMAP H2 BSP" introduced="9.0">
      <unit bldFile="os\boardsupport\omaph2\omaph2bsp\h2" mrp="os\boardsupport\omaph2\omaph2bsp\h2\base_omaph2.mrp"/>
     </component>
     <component name="omaph2unistore2" long-name="OMAP H2 UniStore2" filter="gt" introduced="9.1">
      <unit bldFile="os\boardsupport\omaph2\omaph2unistore2" mrp="os\boardsupport\omaph2\omaph2unistore2\base_h2_unistore2.mrp"/>
     </component>
     <component name="omaph2sdio" long-name="OMAP H2 SDIO" filter="gt" introduced="9.2">
      <unit bldFile="os\boardsupport\omaph2\omaph2sdio" mrp="os\boardsupport\omaph2\omaph2sdio\base_h2_sdio.mrp"/>
     </component>
    </collection>
    <collection name="omaph4" long-name="OMAP H4" level="bsp">
     <component name="omaph4bsp" long-name="OMAP H4 BSP">
      <unit bldFile="os\boardsupport\omaph4\omaph4bsp\h4" mrp="os\boardsupport\omaph4\omaph4bsp\h4\base_omaph4hrp.mrp"/>
     </component>
     <component name="h4bootloader" long-name="H4 Boot Loader" introduced="9.1">
      <unit mrp="os\boardsupport\omaph4\h4bootloader\base_omaph4hrp_bootldr.mrp" bldFile="os\boardsupport\omaph4\h4bootloader"/>
     </component>
     <component name="omaph4minienvbootloader" long-name="OMAP H4 Mini Environment Boot Loader" introduced="9.2">
      <unit mrp="os\boardsupport\omaph4\omaph4minienvbootloader\base_omaph4hrp_mebootldr.mrp" bldFile="os\boardsupport\omaph4\omaph4minienvbootloader"/>
     </component>
     <component name="omaph4unistore2" long-name="OMAP H4 Unistore2" filter="gt" introduced="9.2">
      <unit bldFile="os\boardsupport\omaph4\omaph4unistore2" mrp="os\boardsupport\omaph4\omaph4unistore2\base_omaph4hrp_unistore2.mrp"/>
     </component>
     <component name="omaph4sdio" long-name="OMAP H4 SDIO" filter="gt" introduced="9.2">
      <unit bldFile="os\boardsupport\omaph4\omaph4sdio" mrp="os\boardsupport\omaph4\omaph4sdio\base_omaph4hrp_sdio.mrp"/>
     </component>
    </collection>
    <collection name="haitest" long-name="HAI Test Suites" level="test">
     <component name="bspsvs" long-name="BSP Verification Suite" class="placeholder test" introduced="Saffron">
      <!-- PLACEHOLDER="DS.1603"
			<unit mrp="os/boardsupport/haitest/group/bspsvs.mrp"/>
			-->
     </component>
    </collection>
   </block>
   <block name="buildtools" long-name="Build Tools" level="hw" levels="bld mw fw ui">
    <collection name="bldsystemtools" long-name="Build System Tools" level="bld">
     <component name="buildsystemtools" long-name="Build System Tools">
      <unit bldFile="os\buildtools\bldsystemtools\buildsystemtools\group" mrp="os\buildtools\bldsystemtools\buildsystemtools\group\tools_build.mrp"/>
     </component>
     <component name="gttechviewbaseline" long-name="GT Techview Baseline">
      <unit mrp="os\buildtools\packaging\additionalutils\gt_techview_baseline.mrp"/>
     </component>
     <component name="commonbldutils" long-name="Common Utils">
      <unit mrp="os\buildtools\bldsystemtools\commonbldutils\tools_utils_common.mrp"/>
     </component>
    </collection>
    <collection name="packaging" long-name="Packaging" level="ui">
     <component name="additionalutils" long-name="Additional Utils">
      <unit mrp="os\buildtools\packaging\additionalutils\additional_unknown_cedar.mrp"/>
     </component>
    </collection>
    <collection name="toolsandutils" long-name="Tools and Utils" level="mw">
     <component name="productionbldtools" long-name="Production Build Tools" filter="gt">
      <unit mrp="os\buildtools\toolsandutils\productionbldtools\product_tools.mrp"/>
     </component>
     <component name="ctsfunctionalitycheckers" long-name="CTS Functionality Checkers">
      <unit mrp="os\buildtools\toolsandutils\ctsfunctionalitycheckers\Group\testtools_cts_functionalitycheckers.mrp"/>
     </component>
     <component name="burtestserver" long-name="BUR Test Server">
      <unit bldFile="os\buildtools\toolsandutils\burtestserver\Group" mrp="os\buildtools\toolsandutils\burtestserver\Group\testtools_burtestserver.mrp"/>
     </component>
     <component name="cbrtools" long-name="Component Based Release (CBR) Tools" filter="gt">
      <unit bldFile="os\buildtools\toolsandutils\cbrtools\group" mrp="os\buildtools\toolsandutils\cbrtools\group\tools_cbr_tools.mrp"/>
     </component>
     <component name="prf" long-name="Product Realisation Framework">
      <unit bldFile="os\buildtools\toolsandutils\prf\group" mrp="os\buildtools\toolsandutils\prf\group\tools_cbr_prf.mrp"/>
     </component>
     <component name="cdb" long-name="Code Database">
      <unit bldFile="os\buildtools\toolsandutils\cdb\group" mrp="os\buildtools\toolsandutils\cdb\group\testtools_cdb.mrp"/>
     </component>
     <component name="e32tools" long-name="E32 Tools" class="PC" deprecated="tb91">
      <unit bldFile="os\buildtools\toolsandutils\e32tools\group" mrp="os\buildtools\toolsandutils\e32tools\group\tools_e32tools.mrp"/>
     </component>
     <component name="kitcomparator" long-name="Kit Comparator">
      <unit bldFile="os\buildtools\toolsandutils\kitcomparator\group" mrp="os\buildtools\toolsandutils\kitcomparator\group\testtools_cts_kitcomparator.mrp"/>
     </component>
     <component name="wincredistribution" long-name="WinC Redistribution">
      <unit mrp="os\buildtools\dist_os\redistributionwinceka2\tools_redistribution_winc.mrp"/>
     </component>
     <component name="additionalredistribution" long-name="Additional Redistribution">
      <unit mrp="os\buildtools\perltoolsplat_os\redistribution\additional_tools.mrp"/>
     </component>
     <component name="testdriver" long-name="Test Driver">
      <unit bldFile="os\buildtools\toolsandutils\testdriver\Group" mrp="os\buildtools\toolsandutils\testdriver\Group\testtools_testdriver.mrp"/>
     </component>
     <component name="statapi" long-name="STAT API" filter="gt">
      <unit bldFile="os\buildtools\toolsandutils\statapi\source\statapi\console" mrp="os\buildtools\toolsandutils\statapi\group\testtools_stat_device_gt.mrp"/>
     </component>
     <component name="statsource" long-name="STAT Source" filter="gt">
      <unit mrp="os\buildtools\toolsandutils\statsource\group\testtools_stat_common_source.mrp"/>
     </component>
     <component name="statdesktop" long-name="STAT Desktop" filter="gt">
      <unit bldFile="os\buildtools\toolsandutils\statdesktop\group" mrp="os\buildtools\toolsandutils\statdesktop\group\testtools_stat_desktop.mrp"/>
     </component>
     <component name="systemmonitor" long-name="System Monitor" introduced="8.0">
      <unit bldFile="os\buildtools\toolsandutils\systemmonitor\group" mrp="os\buildtools\toolsandutils\systemmonitor\group\testtools_systemmonitor.mrp"/>
     </component>
     <component name="testtoolsdesktop" long-name="Test Tools Desktop" filter="gt" deprecated="tb91">
      <unit bldFile="os\buildtools\toolsandutils\testtoolsdesktop\group" mrp="os\buildtools\toolsandutils\testtoolsdesktop\group\testtools_desktop.mrp"/>
     </component>
     <component name="wintunnel" long-name="Wintunnel">
      <unit mrp="os\buildtools\toolsandutils\wintunnel\group\testtools_WinTunnel_srconly.mrp"/>
     </component>
     <component name="usecasecontroller" long-name="Use Case Controller">
      <unit bldFile="os\buildtools\toolsandutils\usecasecontroller\BuildScripts\group" mrp="os\buildtools\toolsandutils\usecasecontroller\BuildScripts\group\testtools_ucc.mrp"/>
     </component>
     <component name="autotest" long-name="Autotest">
      <unit bldFile="os\buildtools\toolsandutils\autotest\group" mrp="os\buildtools\toolsandutils\autotest\group\tools_autotest.mrp"/>
     </component>
     <component name="testconfigfileparser" long-name="Test Config File Parser">
      <unit bldFile="os\buildtools\toolsandutils\testconfigfileparser\group" mrp="os\buildtools\toolsandutils\testconfigfileparser\group\tools_testconfigfileparser.mrp"/>
     </component>
     <component name="kitsetupapp" long-name="Kit Setup App" filter="gt">
      <unit mrp="os\buildtools\toolsandutils\kitsetupapp\group\tools_devkits_kitsetupapp.mrp"/>
     </component>
     <component name="navigationpages" long-name="Navigation Pages">
      <unit mrp="os\buildtools\toolsandutils\navigationpages\tools_sdk_eng_NavigationPages.mrp"/>
     </component>
     <component name="productinstaller" long-name="Product Installer" filter="gt">
      <unit bldFile="os\buildtools\toolsandutils\productinstaller\group" mrp="os\buildtools\toolsandutils\productinstaller\group\tools_custkits_productinstaller.mrp"/>
     </component>
     <component name="stlport" long-name="STL Port">
      <unit bldFile="os\buildtools\toolsandutils\stlport\group" mrp="os\buildtools\toolsandutils\stlport\group\tools_stlport.mrp"/>
     </component>
    </collection>
    <collection name="dist_os" long-name="Redistribution" level="mw">
     <component name="redistributionwinceka2" long-name="Redistribution WINC EKA2">
      <unit bldFile="os\buildtools\dist_os\redistributionwinceka2" mrp="os\buildtools\dist_os\redistributionwinceka2\tools_redistribution_cedar.mrp"/>
     </component>
    </collection>
    <collection name="bintools_os" long-name="Binary Tools" level="fw">
     <component name="rcomp" long-name="Resource Compiler">
      <unit bldFile="os\buildtools\bintools_os\rcomp\group" mrp="os\buildtools\bintools_os\rcomp\group\tools_rcomp.mrp"/>
     </component>
     <component name="evalid" long-name="Evalid">
      <unit bldFile="os\buildtools\bintools_os\evalid" mrp="os\buildtools\bintools_os\evalid\tools_evalid.mrp"/>
     </component>
    </collection>
    <collection name="perltoolsplat_os" long-name="Perl Tools Platform" level="mw">
     <component name="redistribution" long-name="Redistribution" filter="gt">
      <unit bldFile="os\buildtools\perltoolsplat_os\redistribution" mrp="os\buildtools\perltoolsplat_os\redistribution\tools_redistribution_common.mrp"/>
     </component>
     <component name="legacycommonperl" long-name="Legacy Common Perl Libraries">
      <unit bldFile="os\buildtools\perltoolsplat_os\legacycommonperl\group" mrp="os\buildtools\perltoolsplat_os\legacycommonperl\group\tools_sdk_eng_perllibrary.mrp"/>
     </component>
     <component name="commonperl" long-name="Common Perl Libraries">
      <unit bldFile="os\buildtools\perltoolsplat_os\commonperl\group" mrp="os\buildtools\perltoolsplat_os\commonperl\group\tools_sdk_eng_perl_shared.mrp"/>
     </component>
    </collection>
    <collection name="sbsv1_os" long-name="Symbian Build System v1" level="fw">
     <component name="e32toolp" long-name="E32 Perl Tools" class="PC">
      <unit mrp="os\buildtools\sbsv1_os\e32toolp\group\tools_e32toolp.mrp"/>
     </component>
     <component name="bldtools" long-name="Build Tools" filter="gt">
      <unit bldFile="os\buildtools\sbsv1_os\bldtools\group" mrp="os\buildtools\sbsv1_os\bldtools\group\tools_sdk_eng_build-tools.mrp"/>
     </component>
    </collection>
    <collection name="srcanamdw_os" long-name="Source Analysis Middleware" level="fw">
     <component name="leavescan" long-name="Leavescan">
      <unit bldFile="os\buildtools\srcanamdw_os\leavescan\group" mrp="os\buildtools\srcanamdw_os\leavescan\group\testtools_leavescan.mrp"/>
     </component>
     <component name="programchecker" long-name="Program Checker" deprecated="tb91">
      <unit bldFile="os\buildtools\srcanamdw_os\programchecker\group" mrp="os\buildtools\srcanamdw_os\programchecker\group\testtools_programchecker.mrp"/>
     </component>
     <component name="migrationtool" long-name="Migration Tool">
      <unit bldFile="os\buildtools\srcanamdw_os\migrationtool\group" mrp="os\buildtools\srcanamdw_os\migrationtool\group\testtools_migrationtool.mrp"/>
     </component>
    </collection>
    <collection name="imgtools_os" long-name="Image Tools" level="fw">
     <component name="romkiteka2" long-name="ROMKIT EKA2" deprecated="tb91">
      <unit bldFile="os\buildtools\imgtools_os\romkiteka2\group" mrp="os\buildtools\imgtools_os\romkiteka2\group\tools_romkit.mrp"/>
     </component>
    </collection>
    <collection name="binanamdw_os" long-name="Binary Analysis Middleware" level="fw">
     <component name="captools" long-name="Capability Tools">
      <unit bldFile="os\buildtools\binanamdw_os\captools\group" mrp="os\buildtools\binanamdw_os\captools\group\testtools_captools.mrp"/>
     </component>
     <component name="depcheck" long-name="Dependency Checker">
      <unit bldFile="os\buildtools\binanamdw_os\depcheck" mrp="os\buildtools\binanamdw_os\depcheck\tools_depcheck.mrp"/>
     </component>
    </collection>
    <collection name="devlib" long-name="Developer Library" level="ui">
     <component name="devlibhelp" long-name="Developer Library Help">
      <unit version="9.4" bldFile="os\buildtools\devlib\devlibhelp\group\devlib94" mrp="os\buildtools\devlib\devlibhelp\group\devlib94\developerlibrary_doc_html.mrp"/>
     </component>
     <component name="devlibsrc" long-name="Developer Library Source" filter="gt">
      <unit bldFile="os\buildtools\devlib\devlibhelp\securitysupplement\doc_source" mrp="os\buildtools\devlib\devlibhelp\developerlibrary_doc_source.mrp"/>
     </component>
     <component name="devlibhtml" long-name="Developer Library HTML">
      <unit mrp="os\buildtools\devlib\devlibhelp\group\shared\developerlibrary_doc_plain_html.mrp"/>
     </component>
     <component name="toolsdocs" long-name="Tools Documentation">
      <unit mrp="os\buildtools\devlib\toolsdocs\tools_documentation.mrp"/>
     </component>
    </collection>
    <collection name="misccomponents" long-name="Misc Components" level="mw">
     <component name="runperl" long-name="Run PERL" filter="gt">
      <unit bldFile="os\buildtools\misccomponents\runperl\group" mrp="os\buildtools\misccomponents\runperl\group\tools_sdk_eng_runperl.mrp"/>
     </component>
     <component name="assertion" long-name="Assertion" filter="gt">