<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SystemDefinition [
 <!ELEMENT SystemDefinition (systemModel?, build?)>
 <!ATTLIST SystemDefinition
  name CDATA #REQUIRED
  schema CDATA #REQUIRED>
 <!ELEMENT systemModel (layer+)>
 <!ELEMENT layer (logicalset* | module*)*>
 <!ATTLIST layer
  name CDATA #REQUIRED
  levels CDATA #IMPLIED
  span CDATA #IMPLIED>
 <!ELEMENT logicalset (logicalsubset* | module* | unit* | package* | prebuilt*)*>
 <!ATTLIST logicalset name CDATA #REQUIRED>
 <!ELEMENT logicalsubset (module* | unit* | package* | prebuilt*)*>
 <!ATTLIST logicalsubset name CDATA #REQUIRED>
 <!ELEMENT module (component* | unit* | package* | prebuilt*)*>
 <!ATTLIST module
  name CDATA #REQUIRED
  level CDATA #IMPLIED>
 <!ELEMENT component (unit* | package* | prebuilt*)*>
 <!ATTLIST component name CDATA #REQUIRED>
 <!ELEMENT unit EMPTY>
 <!ATTLIST unit
  unitID ID #REQUIRED
  name CDATA #REQUIRED
  mrp CDATA #REQUIRED
  filter CDATA #IMPLIED
  bldFile CDATA #REQUIRED
  priority CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT package EMPTY>
 <!ATTLIST package
  name CDATA #REQUIRED
  mrp CDATA #REQUIRED
  filter CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT prebuilt EMPTY>
 <!ATTLIST prebuilt
  name CDATA #REQUIRED
  version CDATA #REQUIRED
  late (Y|N) #IMPLIED
  filter CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT build (option* | target+ | targetList+ | unitList+ | configuration+)*>
 <!ELEMENT unitList (unitRef+)>
 <!ATTLIST unitList
  name ID #REQUIRED
  description CDATA #REQUIRED>
 <!ELEMENT unitRef EMPTY>
 <!ATTLIST unitRef unit IDREF #REQUIRED>
 <!ELEMENT targetList EMPTY>
 <!ATTLIST targetList
  name ID #REQUIRED
  description CDATA #REQUIRED
  target IDREFS #REQUIRED>
 <!ELEMENT target EMPTY>
 <!ATTLIST target
  name ID #REQUIRED
  abldTarget CDATA #REQUIRED
  description CDATA #REQUIRED>
 <!ELEMENT option EMPTY>
 <!ATTLIST option
  name ID #REQUIRED
  abldOption CDATA #REQUIRED
  description CDATA #REQUIRED
  enable (Y | N | y | n) #REQUIRED>
 <!ELEMENT configuration (unitListRef+ | layerRef+ | task+)*>
 <!ATTLIST configuration
  name ID #REQUIRED
  description CDATA #REQUIRED
  filter CDATA #REQUIRED>
 <!ELEMENT task ( unitListRef* , (buildLayer | specialInstructions))>
 <!ELEMENT unitListRef EMPTY>
 <!ATTLIST unitListRef unitList IDREF #REQUIRED>
 <!ELEMENT layerRef EMPTY>
 <!ATTLIST layerRef layerName CDATA #REQUIRED>
 <!ELEMENT buildLayer EMPTY>
 <!ATTLIST buildLayer
  command CDATA #REQUIRED
  targetList IDREFS #IMPLIED
  unitParallel (Y | N | y | n) #REQUIRED
  targetParallel (Y | N | y | n) #IMPLIED>
 <!ELEMENT specialInstructions EMPTY>
 <!ATTLIST specialInstructions
  name CDATA #REQUIRED
  cwd CDATA #REQUIRED
  command CDATA #REQUIRED>
]>
<!-- 
============================================================================ 
Name        : sysdef_dtd_1_4_0.xml 
Part of     : Helium 
Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
All rights reserved.
This component and the accompanying materials are made available
under the terms of the License "Eclipse Public License v1.0"
which accompanies this distribution, and is available
at the URL "http://www.eclipse.org/legal/epl-v10.html".
Initial Contributors:
Nokia Corporation - initial contribution.
Contributors:
Description:
============================================================================
-->
<SystemDefinition name="sysdef_dtd_1_4_0_xml + devicesync + eas + QuickOffice + adobereader + tfxserver + webvideo + wmdrmkeystorage_dist + wmdrmpd_dist + zipviewer + webservde + oemrndtools + swconfigapps + toolsextensions + avdomain + btaudioadaptation_stub + drm_stub + ocrsrv_stub + omasuplasnconverterstubimpl + posmsgpluginreferenceimpl + power_save_display_mode_stub + srsfenginestub + systemswstubs + tactileclickplugin_stub + wlanhwinit_stub + camera + commonemail + conntools + contacts + contentcontrol + conversations + devicecontrol + systemswextensions + files + gallery + graphicsuis + helps + homescreen + im + imgeditor + imgvieweruis + iptelephony + java + location + messaging + mmsharinguis + avdomain + organizer + phone + photos + printing + profile + radio + rndtools + screensaver + settingsuis + speechsrv + utils + videocenter + videoeditor + avdomain + videotelephony + avdomain + webuis + accesssec + appinstall + appsupport + btservices + camerasrv + classicui + dlnasrv + drm + hapticsservices + avdomain + homescreensrv + imghandling + imsrv + inputmethods + ipappprotocols + ipappservices + ipconnmgmt + legacypresence + locationsrv + mds + messagingmw + metadatasrv + avdomain + avdomain + mmuifw + netprotocols + networkingdm + opensrv + phonesrv + platformtools + remoteconn + remotemgmt + remotestorage + securitysrv + serviceapi + serviceapifw + shortlinkconn + ossrv + svgt + uiaccelerator + uiresources + uitools + usbservices + videoutils + vpnclient + web + websrv + wirelessacc + cellularsrv + S60Extras + devicesrv + graphics + imagingext + lbs + avdomainosext + networkingsrv + osrndtools + ossrv + shortlinksrv + systemswextensions + wlan + xmlsrv + buildplatforms + homescreentools + swconfigtools" schema="1.4.0"><systemModel>
    <layer name="app_layer">
      <module name="devicesync">
        <unit unitID="spdo.devicesync" mrp="" bldFile="ext/app/devicesync/group" filter="dfs_build" name="devicesync"/>
      </module>
<module name="eas">
        <unit unitID="EDo.eas" mrp="" bldFile="ext/app/eas/group" name="eas" filter="dfs_build"/>
      </module>
<module name="oemrndtools">
        <unit unitID="tools.oemrndtools" mrp="" bldFile="ext/tools/oemrndtools/group" name="oemrndtools"/>
      </module>
<module name="">
      <unit unitID="tools.oemrndtools.trk" mrp="" bldFile="ext/tools/oemrndtools/trk/group" filter="oem_build" name="tools_oemrndtools_trk"/>
<unit unitID="java.java.java_plat" mrp="" bldFile="sf/app/java/java_plat/group" filter="sf_build" name="java_java_plat"/>
<unit unitID="java.java.java_stubs" mrp="" bldFile="sf/app/java/java_stubs/group" filter="sf_build" name="java_java_stubs"/>
<unit unitID="tools.rndtools.htiui" mrp="" bldFile="sf/app/rndtools/htiui/group" filter="sf_build" name="tools_rndtools_htiui"/></module>
<module name="swconfigapps">
        <unit unitID="tools.swconfigapps" mrp="" bldFile="ext/tools/swconfigapps/group" name="swconfigapps"/>
      </module>
<module name="camera">
        <unit unitID="imm.camera" mrp="" bldFile="sf/app/camera/group" name="camera"/>
        <unit unitID="imm.camera.help" mrp="" bldFile="sf/app/camera/camerauis/cameraapp/help/group" name="camera_help"/>
      </module>
<module name="commonemail">
        <unit unitID="EDo.commonemail" mrp="" bldFile="sf/app/commonemail/group" name="commonemail"/>
      </module>
<module name="conntools">
        <unit unitID="netdo.conntools" mrp="" bldFile="sf/app/conntools/group" name="conntools"/>
      </module>
<module name="contentcontrol">
        <unit unitID="spdo.contentcontrol" mrp="" bldFile="sf/app/contentcontrol/group" name="contentcontrol"/>
      </module>
<module name="conversations">
        <unit unitID="MeCodo.conversations" mrp="" bldFile="sf/app/conversations/group" name="conversations"/>
      </module>
<module name="devicecontrol">
        <unit unitID="spdo.devicecontrol" mrp="" bldFile="sf/app/devicecontrol/group" name="devicecontrol"/>
      </module>
<module name="dictionary">
        <unit unitID="abs.dictionary" mrp="" bldFile="sf/app/dictionary/group" name="dictionary"/>
      </module>
<module name="files">
        <unit name="files" unitID="sydo.files" bldFile="sf/app/files/group" mrp=""/>
      </module>
<module name="gallery">
        <unit unitID="imm.gallery" mrp="" bldFile="sf/app/gallery/group" name="gallery"/>
      </module>
<module name="graphicsuis">
        <unit unitID="abs.graphicsuis" mrp="" bldFile="sf/app/graphicsuis/group" name="graphicsuis"/>
      </module>
<module name="helps">
        <unit unitID="abs.helps" mrp="" bldFile="sf/app/helps/group" name="helps"/>
      </module>
<module name="homescreen">
        <unit unitID="abs.homescreen" mrp="" bldFile="sf/app/homescreen/group" name="homescreen"/>
      </module>
<module name="im">
        <unit unitID="impp.im" mrp="" bldFile="sf/app/im/group" name="im"/>
      </module>
<module name="imgeditor">
        <unit unitID="imm.imgeditor" mrp="" bldFile="sf/app/imgeditor/group" name="imgeditor"/>
      </module>
<module name="imgvieweruis">
        <unit unitID="imm.imgvieweruis" mrp="" bldFile="sf/app/imgvieweruis/group" name="imgvieweruis"/>
      </module>
<module name="iptelephony">
        <unit name="iptelephony" unitID="te.iptelephony" bldFile="sf/app/iptelephony/group" mrp=""/>
      </module>
<module name="java">
        <unit unitID="java.java" mrp="" bldFile="sf/app/java/group" filter="!sf_build" name="java"/>
      </module>
<module name="location">
        <unit unitID="lodo.location" mrp="" bldFile="sf/app/location/group" name="location"/>
      </module>
<module name="messaging">
        <unit unitID="Medo.messaging" mrp="" bldFile="sf/app/messaging/group" name="messaging"/>
      </module>
<module name="mmsharinguis">
  		<unit unitID="msdo.mmsharinguis" name="mmsharinguis" bldFile="\sf\app\mmsharinguis\group" mrp=""/> 
      </module>
<module name="musicplayer">
				<unit unitID="musicplayer" mrp="" bldFile="sf/app/musicplayer/group" name="musicplayer"/>
			</module>
<module name="organizer">
        <unit unitID="orgdo.organizer" mrp="" bldFile="sf/app/organizer/group" name="organizer"/>
      </module>
<module name="phone">
        <unit name="phone" unitID="tedo.phone" bldFile="sf/app/phone/group" mrp=""/>
      </module>
<module name="photos">
        <unit unitID="uxdo.photos" mrp="" bldFile="sf/app/photos/group" name="photos"/>
      </module>
<module name="printing">
        <unit unitID="lcdo.printing" mrp="" bldFile="sf/app/printing/group" name="printing"/>
      </module>
<module name="profile">
        <unit name="profile" unitID="presdo.profile" bldFile="sf/app/profile/group" mrp=""/>
      </module>
<module name="radio">
        <unit unitID="vado.radio" mrp="" bldFile="sf/app/radio/group" name="radio"/>
      </module>
<module name="rndtools">
        <unit unitID="tools.rndtools" mrp="" bldFile="sf/app/rndtools/group" name="rndtools"/>
      </module>
<module name="screensaver">
        <unit unitID="abs.screensaver" mrp="" bldFile="sf/app/screensaver/group" name="screensaver"/>
      </module>
<module name="settingsuis">
      <unit name="settingsuis" unitID="presdo.settingsuis" bldFile="sf/app/settingsuis/group" mrp=""/>
      </module>
<module name="speechsrv">
        <unit unitID="MuiDo.speechsrv" mrp="" bldFile="sf/app/speechsrv/group" name="speechsrv"/>
      </module>
<module name="utils">
        <unit unitID="orgdo.utils" mrp="" bldFile="sf/app/utils/group" name="utils"/>
      </module>
<module name="videocenter">
        <unit unitID="vado.videocenter" mrp="" bldFile="sf/app/videocenter/group" name="videocenter"/>
      </module>
<module name="videoeditor">
        <unit unitID="imm.videoeditor" mrp="" bldFile="sf/app/videoeditor/group" name="videoeditor"/>
      </module>
<module name="videoplayer">
				<unit unitID="videoplayer" mrp="" bldFile="sf/app/videoplayer/group" name="videoplayer"/>
			</module>
<module name="videotelephony">
        <unit name="videotelephony_plat" unitID="tedo.videotelephony_plat" bldFile="sf/app/videotelephony/videotelephony_plat/group" mrp=""/>
        <unit name="PacketVideoEngineBinaries" unitID="tedo.PacketVideoEngineBinaries" bldFile="sf/app/videotelephony/packetvideoengine/PacketVideoEngineBinaries/group" mrp="" filter="!sf_build"/> 
        <unit name="vtprotocolsstub" unitID="tedo.vtprotocolsstub" bldFile="sf/app/videotelephony/vtprotocolsstub/group" mrp="" filter="sf_build"/>  
        <unit name="vtprotocols" unitID="tedo.vtprotocols" bldFile="sf/app/videotelephony/vtprotocols/group" mrp="" filter="!sf_build"/>
        <unit name="DisplaySink" unitID="tedo.DisplaySink" bldFile="sf/app/videotelephony/vtprotocolplugins/DisplaySink/group" mrp=""/> 
        <unit name="VideoSource" unitID="tedo.VideoSource" bldFile="sf/app/videotelephony/vtprotocolplugins/VideoSource/group" mrp=""/>
        <unit name="videoteleng" unitID="tedo.videoteleng" bldFile="sf/app/videotelephony/vtengines/videoteleng/Group" mrp=""/>  
        <unit name="videotelui" unitID="tedo.videotelui" bldFile="sf/app/videotelephony/vtuis/videotelui/group" mrp=""/> 
	<unit name="vtmediatorplugin" unitID="tedo.vtmediatorplugin" bldFile="sf/app/videotelephony/vtengines/vtmediatorplugin/group" mrp=""/>
      </module>
<module name="voicerec">
				<unit unitID="voicerec" mrp="" bldFile="sf/app/voicerec/group" name="voicerec"/>
			</module>
<module name="webuis">
	    <unit unitID="browsing_domain.webuis" mrp="" bldFile="sf/app/webuis/group" name="webuis"/>
      </module></layer>
<layer name="complementary_layer">
      <module name="QuickOffice">
        <unit unitID="orgdo.QuickOffice" mrp="" bldFile="ext/complementary/QuickOffice/group" name="QuickOffice"/>
      </module>
<module name="adobereader">
        <unit unitID="orgdo.adobereader" mrp="" bldFile="ext/complementary/adobereader/group" name="adobereader"/>
      </module>
<module name="webvideo">
        <unit unitID="wvdo.webvideo" mrp="" bldFile="ext/complementary/webvideo/group" name="webvideo"/>
      </module>
<module name="wmdrmkeystorage_dist">
        <unit unitID="sedo.wmdrmkeystorage_dist" mrp="" bldFile="ext/complementary/wmdrmkeystorage_dist/group" name="wmdrmkeystorage_dist" filter="dfs_build"/>
      </module>
<module name="wmdrmpd_dist">
        <unit unitID="sedo.wmdrmpd_dist" mrp="" bldFile="ext/complementary/wmdrmpd_dist/group" name="wmdrmpd_dist" filter="dfs_build"/>
      </module>
<module name="zipviewer">
        <unit unitID="orgdo.zipviewer" mrp="" bldFile="ext/complementary/zipviewer/group" name="zipviewer"/>
      </module></layer>
<layer name="mw_layer">
      <module name="websrvde">
        <unit unitID="WSDo.websrvde" mrp="" bldFile="ext/mw/websrvde/group" name="websrvde" filter="dfs_build"/>
      </module>
<module name="accesssec">
        <unit unitID="netdo.accesssec" mrp="" bldFile="sf/mw/accesssec/group" name="accesssec"/>
      </module>
<module name="appinstall">
        <unit unitID="sedo.appinstall" mrp="" bldFile="sf/mw/appinstall/group" name="appinstall"/>
      </module>
<module name="appsupport">
        <unit unitID="sydo.appsupport" name="appsupport" bldFile="sf/mw/appsupport/group" mrp=""/>
      </module>
<module name="">
        <unit unitID="sydo.appsupport.appsupport_plat.flash_mmi_service_interface_custom_api" name="sydo_appsupport_appsupport_plat_flash_mmi_service_interface_custom_api" bldFile="sf/mw/appsupport/appsupport_plat/flash_mmi_service_interface_custom_api/group" mrp="" filter="!sf_build"/>
        <unit unitID="sydo.appsupport.appsupport_plat.flash_netscape_plugin_command_api" name="sydo_appsupport_appsupport_plat_flash_netscape_plugin_command_api" bldFile="sf/mw/appsupport/appsupport_plat/flash_netscape_plugin_command_api/group" mrp="" filter="!sf_build"/>
<unit unitID="mmmw_3GPExtParserLib" mrp="" bldFile="sf/mw/mmmw/metadatautility/3GPExtParserLib/group" filter="!sf_build" name="mmmw_3GPExtParserLib"/>
<unit unitID="mtp" mrp="" bldFile="sf/mw/mmmw/mtp/group" filter="!sf_build" name="mtp"/>
<unit unitID="helix_stub" mrp="" bldFile="sf/mw/mmmw/mmfw/helix_stub/group" filter="sf_build" name="helix_stub"/>
<unit unitID="sedo.securitysrv.pkiutilities.Certificates" bldFile="sf/mw/securitysrv/pkiutilities/Certificates/group" mrp="" filter="sf_build" name="sedo_securitysrv_pkiutilities_Certificates"/>
<unit unitID="sedo.securitysrv.pkiutilities.Certificates_OEM" bldFile="sf/mw/securitysrv/pkiutilities/Certificates_OEM/group" mrp="" filter="oem_build" name="sedo_securitysrv_pkiutilities_Certificates_OEM"/>
<unit unitID="lcdo.usbservices.usbclasses.usbosdescriptorhandler" mrp="" bldFile="\sf\mw\usbservices\usbclasses\usbosdescriptorhandler\group" filter="!sf_build" name="usbservices_usbclasses_usbosdescriptorhandler"/></module>
<module name="btservices">
        <unit unitID="lcdo.btservices" mrp="" bldFile="\sf\mw\btservices\group" name="btservices"/>
      </module>
<module name="camerasrv">
        <unit unitID="imm.camerasrv" mrp="" bldFile="sf/mw/camerasrv/group" name="camerasrv"/>
      </module>
<module name="dlnasrv">
        <unit name="homemedia" unitID="hcdo.homemedia" bldFile="sf/mw/dlnasrv/homemedia/group" mrp=""/>
        <unit name="homesync" unitID="hcdo.homesync" bldFile="sf/mw/dlnasrv/homesync/group" mrp=""/>
        <unit name="upnpavcontrolpoint" unitID="hcdo.upnpavcontrolpoint" bldFile="sf/mw/dlnasrv/upnpavcontrolpoint/group" mrp=""/>
        <unit name="upnpframework" unitID="hcdo.upnpframework" bldFile="sf/mw/dlnasrv/upnpframework/group" mrp=""/>
        <unit name="upnpharvester" unitID="hcdo.upnpharvester" bldFile="sf/mw/dlnasrv/upnpharvester/group" mrp=""/>
        <unit name="upnpmediaserver" unitID="hcdo.upnpmediaserver" bldFile="sf/mw/dlnasrv/upnpmediaserver/group" mrp=""/>
        <unit name="upnpavcontroller" unitID="hcdo.upnpavcontroller" bldFile="sf/mw/dlnasrv/upnpavcontroller/group" mrp=""/>
        <unit name="upnpsharing" unitID="hcdo.upnpsharing" bldFile="sf/mw/dlnasrv/upnpsharing/group" mrp=""/>
        <unit name="upnpsettings" unitID="hcdo.upnpsettings" bldFile="sf/mw/dlnasrv/upnpsettings/group" mrp=""/>
        <unit name="upnpmpxplugins" unitID="hcdo.upnpmpxplugins" bldFile="sf/mw/dlnasrv/upnpmpxplugins/group" mrp=""/>
        <unit name="dlnasrv_plat" unitID="hcdo.dlnasrv_plat" bldFile="sf/mw/dlnasrv/dlnasrv_plat/group" mrp=""/>
      </module>
<module name="drm">
        <unit unitID="sedo.drm" mrp="" bldFile="sf/mw/drm/group" name="drm"/>
      </module>
<module name="hapticsservices">
        <unit unitID="abs.hapticsservices" mrp="" bldFile="sf/mw/hapticsservices/group" name="hapticsservices"/>
        <unit unitID="abs.tactilefeedbackresolver" mrp="" bldFile="sf/mw/hapticsservices/tactilefeedback/tactilefeedbackresolver/plugins/group" filter="dfs_build" name="tactilefeedbackresolver"/>
        <unit unitID="abs.tacticonhapticsplugin" mrp="" bldFile="sf/mw/hapticsservices/tacticonserver/server/tacticonpluginfw/tacticonhapticsplugin/group" filter="dfs_build" name="tacticonhapticsplugin"/>
      </module>
<module name="helix">
				<unit unitID="helix" mrp="" bldFile="sf/mw/helix/group" filter="!sf_build" name="helix"/>
				<unit unitID="helix_src" mrp="" bldFile="sf/mw/helix/helix_ren/src/group" filter="!sf_build" name="helix_src"/>
			</module>
<module name="homescreensrv">
        <unit unitID="hs.homescreensrv" mrp="" bldFile="sf/mw/homescreensrv/group" name="homescreensrv"/>
      </module>
<module name="imghandling">
        <unit unitID="imm.imghandling" mrp="" bldFile="sf/mw/imghandling/group" name="imghandling"/>
      </module>
<module name="imsrv">
        <unit unitID="MeCodo.imsrv" mrp="" bldFile="sf/mw/imsrv/group" name="imsrv"/>
      </module>
<module name="inputmethods">
        <unit unitID="abs.inputmethods" mrp="" bldFile="sf/mw/inputmethods/group" name="inputmethods"/>
      </module>
<module name="ipappprotocols">
  		<unit unitID="ipappprotocol" name="ipappprotocol" bldFile="\sf\mw\ipappprotocols\group" mrp=""/> 
      </module>
<module name="ipappsrv">
  		<unit unitID="ipappsrv" name="ipappservice" bldFile="\sf\mw\ipappsrv\group" mrp=""/> 
      </module>
<module name="ipconnmgmt">
        <unit unitID="netdo.ipconnmgmt" mrp="" bldFile="sf/mw/ipconnmgmt/group" name="ipconnmgmt"/>
      </module>
<module name="legacypresence">
        <unit unitID="presdo.legacypresence" mrp="" bldFile="sf/mw/legacypresence/group" name="legacypresence"/>
      </module>
<module name="locationsrv">
        <unit unitID="lodo.locationsrv" mrp="" bldFile="sf/mw/locationsrv/group" name="locationsrv"/>
      </module>
<module name="asnpluginimplementation"> 
     	<unit unitID="lodo.locationsrv.supl.asnpluginimplementation" mrp="" bldFile="sf/mw/locationsrv/supl/locationomasuplprotocolhandler/asnpluginimplementation/group" filter="dfs_build" name="lodo_locationsrv_supl_asnpluginimplementation>"/>
     </module>
<module name="mds">
        <unit unitID="imm.mds" mrp="" bldFile="sf/mw/mds/group" name="mds"/>
      </module>
<module name="messagingmw">
        <unit unitID="Medo.messagingmw" mrp="" bldFile="sf/mw/messagingmw/group" name="messagingmw"/>
      </module>
<module name="metadatasrv">
        <unit unitID="imm.metadatasrv" mrp="" bldFile="sf/mw/metadatasrv/group" name="metadatasrv"/>
      </module>
<module name="mmappfw">
				<unit unitID="mmappfw" mrp="" bldFile="sf/mw/mmappfw/group" name="mmappfw"/>
			</module>
<module name="mmmw">
				<unit unitID="mmmw" mrp="" bldFile="sf/mw/mmmw/group" name="mmmw"/>
			</module>
<module name="mmuifw">
        <unit unitID="uxdo.mmuifw" mrp="" bldFile="sf/mw/mmuifw/group" name="mmuifw"/>
      </module>
<module name="netprotocols">
	    <unit unitID="browsing_domain.netprotocols" mrp="" bldFile="sf/mw/netprotocols/group" name="netprotocols"/>
      </module>
<module name="networkingdm">
        <unit unitID="netdo.networkingdm" mrp="" bldFile="sf/mw/networkingdm/group" name="networkingdm"/>
      </module>
<module name="opensrv">
        <unit unitID="MeCodo.opensrv" mrp="" bldFile="sf/mw/opensrv/group" name="opensrv"/>
      </module>
<module name="phonesrv">
	      <unit name="phonesrv_plat" unitID="tedo.phonesrv_plat" bldFile="sf/mw/phonesrv/phonesrv_plat/group" mrp=""/>
        <unit name="phonesrv_pub" unitID="tedo.phonesrv_pub" bldFile="sf/mw/phonesrv/phonesrv_pub/group" mrp=""/>
        <unit name="CbsServer" unitID="tedo.CbsServer" bldFile="sf/mw/phonesrv/cbs/CbsServer/group" mrp=""/>
        <unit name="cbsui" unitID="tedo.cbsui" bldFile="sf/mw/phonesrv/cbs/cbsui/group" mrp=""/>
        <unit name="convergedcallengine" unitID="tedo.convergedcallengine" bldFile="sf/mw/phonesrv/convergedcallengine/group" mrp=""/>
        <unit name="networkhandlingengine" unitID="tedo.networkhandlingengine" bldFile="sf/mw/phonesrv/networkhandling/networkhandlingengine/group" mrp=""/>
        <unit name="aiwdialdata" unitID="tedo.aiwdialdata" bldFile="sf/mw/phonesrv/phoneclientserver/aiwdialdata/group" mrp=""/>
        <unit name="CallUI" unitID="tedo.CallUI" bldFile="sf/mw/phonesrv/phoneclientserver/CallUI/group" mrp=""/>
        <unit name="dialutils" unitID="tedo.dialutils" bldFile="sf/mw/phonesrv/phoneclientserver/dialutils/group" mrp=""/>
        <unit name="EnPolicy" unitID="tedo.EnPolicy" bldFile="sf/mw/phonesrv/phoneclientserver/EnPolicy/group" mrp=""/>
        <unit name="phoneclient" unitID="tedo.phoneclient" bldFile="sf/mw/phonesrv/phoneclientserver/phoneclient/group" mrp=""/>
        <unit name="phoneserver" unitID="tedo.phoneserver" bldFile="sf/mw/phonesrv/phoneclientserver/phoneserver/group" mrp=""/>
        <unit name="SatServer" unitID="tedo.SatServer" bldFile="sf/mw/phonesrv/satengine/SatServer/group" mrp=""/>
        <unit name="satapp" unitID="tedo.satapp" bldFile="sf/mw/phonesrv/satui/satapp/group" mrp=""/>
        <unit name="satplugin" unitID="tedo.satplugin" bldFile="sf/mw/phonesrv/satui/satplugin/group" mrp=""/>
        <unit name="phoneparser" unitID="tedo.phoneparser" bldFile="sf/mw/phonesrv/telutils/phoneparser/group" mrp=""/>
				<unit name="telephonyservice" unitID="tedo.telephonyservice" bldFile="sf/mw/phonesrv/telutils/telephonyservice/group" mrp=""/>
        <unit name="telephonysettings" unitID="tedo.telephonysettings" bldFile="sf/mw/phonesrv/cellular/telephonysettings/group" mrp=""/>
        <unit name="sssettings" unitID="tedo.sssettings" bldFile="sf/mw/phonesrv/cellular/sssettings/group" mrp=""/>
        <unit name="psetnotesui" unitID="tedo.psetnotesui" bldFile="sf/mw/phonesrv/cellular/psetnotesui/group" mrp=""/>
        <unit name="servicerequest" unitID="tedo.servicerequest" bldFile="sf/mw/phonesrv/cellular/servicerequest/group" mrp=""/>
				<unit name="phonecmdhnlr" unitID="tedo.phonecmdhnlr" bldFile="sf/mw/phonesrv/phonecmdhandler/phonecmdhnlr/group" mrp=""/>
				<unit name="vmbxengine" unitID="tedo.vmbxengine" bldFile="sf/mw/phonesrv/engines/vmbxengine/group" mrp=""/>
      </module>
<module name="platformtools">
        <unit unitID="tools.platformtools" mrp="" bldFile="sf/mw/platformtools/group" name="platformtools"/>
      </module>
<module name="remoteconn">
        <unit name="remoteconn" unitID="sydo.remoteconn" bldFile="sf/mw/remoteconn/group" mrp=""/>
      </module>
<module name="remotemgmt">
        <unit unitID="spdo.remotemgmt" mrp="" bldFile="sf/mw/remotemgmt/group" name="remotemgmt"/>
      </module>
<module name="remotestorage">
        <unit unitID="presdo.remotestorage" mrp="" bldFile="sf/mw/remotestorage/group" name="remotestorage"/>
      </module>
<module name="securitysrv">
        <unit name="securitysrv" unitID="sedo.securitysrv" bldFile="sf/mw/securitysrv/group" mrp=""/>
      </module>
<module name="serviceapi">                             
<unit name="serviceapi" unitID="sapido.serviceapi" bldFile="sf/mw/serviceapi/group" mrp=""/>
</module>
<module name="serviceapifw">                             
<unit name="serviceapifw" unitID="sapido.serviceapifw" bldFile="sf/mw/serviceapifw/group" mrp=""/>
</module>
<module name="shortlinkconn">
        <unit unitID="lcdo.shortlinkconn" mrp="" bldFile="\sf\mw\shortlinkconn\group" name="shortlinkconn"/>
      </module>
<module name="upnp">                             
<unit name="upnp" unitID="mrtdo.upnp" bldFile="sf/mw/srvdiscovery/upnp/group" mrp=""/>
</module>
<module name="svgt">
        <unit unitID="abs.svgt" mrp="" bldFile="sf/mw/svgt/group" name="svgt"/>
      </module>
<module name="uiaccelerator">
        <unit unitID="abs.uiaccelerator" mrp="" bldFile="sf/mw/uiaccelerator/group" name="uiaccelerator"/>
      </module>
<module name="uiresources">
        <unit unitID="abs.uiresources" mrp="" bldFile="sf/mw/uiresources/group" name="uiresources"/>
      </module>
<module name="usbservices">
        <unit unitID="lcdo.usbservices" mrp="" bldFile="\sf\mw\usbservices\group" name="usbservices"/>
      </module>
<module name="videoutils">
        <unit unitID="vado.videoutils" mrp="" bldFile="sf/mw/videoutils/group" name="videoutils"/>
      </module>
<module name="vpnclient"> 
     	<unit unitID="netdo.vpnclient" mrp="" bldFile="sf/mw/vpnclient/group" filter="!oem_build" name="vpnclient"/>
     </module>
<module name="web">
	    <unit unitID="browsing_domain.web" mrp="" bldFile="sf/mw/web/group" name="web"/>
      </module>
<module name="websrv">
        <unit unitID="WSDo.websrv" mrp="" bldFile="sf/mw/websrv/group" name="websrv"/>        
      </module>
<module name="wirelessacc">
        <unit unitID="netdo.wirelessacc" mrp="" bldFile="sf/mw/wirelessacc/group" name="wirelessacc"/>
      </module></layer>
<layer name="os_layer">
      <module name="toolsextensions">
        <unit unitID="tools.toolsextensions" mrp="" bldFile="ext/tools/toolsextensions/group" name="toolsextensions"/>
      </module>
<module name="cellularsrv">
				<unit name="cellularsrv" unitID="tsydo.cellularsrv" bldFile="sf/os/cellularsrv/group" mrp=""/>       
       </module>
<module name="S60Extras">
        <unit unitID="platform.S60Extras" mrp="" bldFile="sf/os/deviceplatformrelease/S60Extras/group" name="S60Extras"/>
      </module>
<module name="S60LocFiles">
        <unit unitID="platform.S60LocFiles" mrp="" bldFile="sf/os/deviceplatformrelease/S60LocFiles/group" filter="sf_build" name="S60LocFiles"/>
        <unit unitID="platform.S60LocFiles_oem" mrp="" bldFile="sf/os/deviceplatformrelease/S60LocFiles/group_oem" filter="!sf_build" name="group_oem"/>
      </module>
<module name="version">
        <unit unitID="platform.version" mrp="" bldFile="sf/os/deviceplatformrelease/Version/group" name="version"/>
      </module>
<module name="devicesrv">                                                                                                                            
        <unit unitID="sydo.devicesrv" mrp="" bldFile="sf/os/devicesrv/group" name="devicesrv"/>                  
      </module>
<module name="">
          <unit unitID="sydo.devicesrv.hapticsvibepacketizerplugin" mrp="" bldFile="sf/os/devicesrv/hwrmhaptics/hapticspacketizer/plugins/hapticsvibepacketizerplugin/group" name="sydo_devicesrv_hapticsvibepacketizerplugin" filter="dfs_build"/>
          <unit unitID="sydo.devicesrv.hapticsivtgetterplugin" mrp="" bldFile="sf/os/devicesrv/hwrmhaptics/hapticseffectdatagetterfw/plugins/hapticsivtgetterplugin/group" name="sydo_devicesrv_hapticsivtgetterplugin" filter="dfs_build"/>
<unit unitID="imm.imagingext.imagingmodules.videoencpluginarm" mrp="" bldFile="sf/os/imagingext/imagingmodules/VideoEncPluginARM/Build" filter="oem_build" name="imm_imagingext_imagingmodules_videoencpluginarm"/>
<unit unitID="imm.imagingext.imagingmodules.h264avcvideoencarm" mrp="" bldFile="sf/os/imagingext/imagingmodules/H264AVCVideoEncARM/group" filter="oem_build" name="imm_imagingext_imagingmodules_h264avcvideoencarm"/>
<unit unitID="AacEncoderPlugin" mrp="" bldFile="sf/os/mm/audio/ARM_CMMF_codecs/AacEncoderPlugin/group" filter="!sf_build" name="AacEncoderPlugin"/>
<unit unitID="AmrNbCodecPlugin" mrp="" bldFile="sf/os/mm/audio/ARM_CMMF_codecs/AmrNbCodecPlugin/group" filter="!sf_build" name="AmrNbCodecPlugin"/>
<unit unitID="AmrWbCodecPlugin" mrp="" bldFile="sf/os/mm/audio/ARM_CMMF_codecs/AmrWbCodecPlugin/group" filter="!sf_build" name="AmrWbCodecPlugin"/>
<unit unitID="EAacPlusCodecPlugin" mrp="" bldFile="sf/os/mm/audio/ARM_CMMF_codecs/EAacPlusCodecPlugin/group" filter="!sf_build" name="EAacPlusCodecPlugin"/>
<unit unitID="MP3CodecPlugin" mrp="" bldFile="sf/os/mm/audio/ARM_CMMF_codecs/MP3CodecPlugin/group" filter="!sf_build" name="MP3CodecPlugin"/>
<unit unitID="WMADecoderPlugin" mrp="" bldFile="sf/os/mm/audio/ARM_CMMF_codecs/WMADecoderPlugin/group" filter="!sf_build" name="WMADecoderPlugin"/>