<?xml version="1.0"?>
<!DOCTYPE SystemDefinition [
 <!ELEMENT SystemDefinition (systemModel?, build?)>
 <!ATTLIST SystemDefinition
  name CDATA #REQUIRED
  schema CDATA #REQUIRED>
 <!ELEMENT systemModel (layer+)>
 <!ELEMENT layer (logicalset* | module*)*>
 <!ATTLIST layer
  name CDATA #REQUIRED
  levels CDATA #IMPLIED
  span CDATA #IMPLIED>
 <!ELEMENT logicalset (logicalsubset* | module* | unit* | package* | prebuilt*)*>
 <!ATTLIST logicalset
  name CDATA #REQUIRED
  levels CDATA #IMPLIED
  span CDATA #IMPLIED
  level CDATA #IMPLIED>
 <!ELEMENT logicalsubset (module* | unit* | package* | prebuilt*)*>
 <!ATTLIST logicalsubset name CDATA #REQUIRED>
 <!ELEMENT module (component* | unit* | package* | prebuilt*)*>
 <!ATTLIST module
  name CDATA #REQUIRED
  level CDATA #IMPLIED>
 <!ELEMENT component (unit* | package* | prebuilt*)*>
 <!ATTLIST component name CDATA #REQUIRED>
 <!ELEMENT unit EMPTY>
 <!ATTLIST unit
  unitID ID #REQUIRED
  name CDATA #REQUIRED
  mrp CDATA #REQUIRED
  filter CDATA #IMPLIED
  bldFile CDATA #REQUIRED
  priority CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT package EMPTY>
 <!ATTLIST package
  name CDATA #REQUIRED
  mrp CDATA #REQUIRED
  filter CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT prebuilt EMPTY>
 <!ATTLIST prebuilt
  name CDATA #REQUIRED
  version CDATA #REQUIRED
  late (Y|N) #IMPLIED
  filter CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT build (option* | target+ | targetList+ | unitList+ | configuration+)*>
 <!ELEMENT unitList (unitRef+)>
 <!ATTLIST unitList
  name ID #REQUIRED
  description CDATA #REQUIRED>
 <!ELEMENT unitRef EMPTY>
 <!ATTLIST unitRef unit IDREF #REQUIRED>
 <!ELEMENT targetList EMPTY>
 <!ATTLIST targetList
  name ID #REQUIRED
  description CDATA #REQUIRED
  target IDREFS #REQUIRED>
 <!ELEMENT target EMPTY>
 <!ATTLIST target
  name ID #REQUIRED
  abldTarget CDATA #REQUIRED
  description CDATA #REQUIRED>
 <!ELEMENT option EMPTY>
 <!ATTLIST option
  name ID #REQUIRED
  abldOption CDATA #REQUIRED
  description CDATA #REQUIRED
  enable (Y | N | y | n) #REQUIRED>
 <!ELEMENT configuration (unitListRef+ | layerRef+ | task+)*>
 <!ATTLIST configuration
  name ID #REQUIRED
  description CDATA #REQUIRED
  filter CDATA #REQUIRED>
 <!ELEMENT task ( unitListRef* , (buildLayer | specialInstructions))>
 <!ELEMENT unitListRef EMPTY>
 <!ATTLIST unitListRef unitList IDREF #REQUIRED>
 <!ELEMENT layerRef EMPTY>
 <!ATTLIST layerRef layerName CDATA #REQUIRED>
 <!ELEMENT buildLayer EMPTY>
 <!ATTLIST buildLayer
  command CDATA #REQUIRED
  targetList IDREFS #IMPLIED
  unitParallel (Y | N | y | n) #REQUIRED
  targetParallel (Y | N | y | n) #IMPLIED>
 <!ELEMENT specialInstructions EMPTY>
 <!ATTLIST specialInstructions
  name CDATA #REQUIRED
  cwd CDATA #REQUIRED
  command CDATA #REQUIRED>
]>
<SystemDefinition name="S60_SystemBuild + sysdef_dtd_1_4_0_xml + QuickOffice + adobereader + webvideo + wmdrmkeystorage_dist + wmdrmpd_dist + zipviewer + s60platformrelease + oemrndtools + swconfigapps + avdomain + btaudioadaptation_stub + drm_stub + ocrsrv_stub + omasuplasnconverterstubimpl + posmsgpluginreferenceimpl + power_save_display_mode_stub + srsfenginestub + systemswstubs + tactileclickplugin_stub + wlanhwinit_stub + camera + commonemail + conntools + contacts + contentcontrol + conversations + devicecontrol + systemswextensions + files + gallery + graphicsuis + helps + homescreen + im + imgvieweruis + iptelephony + jrt + location + messaging + mmsharinguis + avdomain + organizer + phone + photos + printing + profile + radio + rndtools + screensaver + settingsuis + speechsrv + graphics + utils + video + videotelephony + avdomain + webuis + accesssec + appinstall + appsupport + btservices + camerasrv + classicui + dlnasrv + drm + gsprofilesrv + hapticsservices + avdomain + homescreensrv + imghandling + imsrv + inputmethods + ipappprotocols + ipappservices + ipconnmgmt + legacypresence + locationsrv + mds + messagingmw + metadatasrv + avdomain + avdomain + mmuifw + netprotocols + networkingdm + opensrv + phonesrv + platformtools + remoteconn + remotemgmt + remotestorage + securitysrv + serviceapi + serviceapifw + shortlinkconn + ossrv + svgt + uiaccelerator + uiresources + uitools + usbservices + videoutils + vpnclient + web + websrv + wirelessacc + bt + cellularsrv + deviceplatformrelease + devicesrv + graphics + imagingext + lbs + avdomainosext + networkingsrv + osrndtools + ossrv + systemswextensions + usb + wlan + xmlsrv + buildplatforms + homescreentools + swconfigtools" schema="1.4.0">
<systemModel>
	<layer name="os_layer">
<module name="bt">
        <unit unitID="lcdo.bt" mrp="" bldFile="sf/os/bt/group" name="bt"/>
      </module>
<module name="cellularsrv">
				<unit name="cellularsrv" unitID="tsydo.cellularsrv" bldFile="sf/os/cellularsrv/group" mrp=""/>       
       </module>
<module name="S60Extras">
        <unit unitID="platform.S60Extras" mrp="" bldFile="sf/os/deviceplatformrelease/S60Extras/group" name="S60Extras"/>
      </module>
<module name="version">
        <unit unitID="platform.version" mrp="" bldFile="sf/os/deviceplatformrelease/Version/group" name="version"/>
      </module>
<module name="sf_cenrep">
        <unit unitID="platform.cenrep" mrp="" bldFile="sf/os/deviceplatformrelease/sf_config/cenrep/group" name="sf_cenrep"/>
      </module>
<module name="devicesrv">                                                                                                                            
        <unit unitID="sydo.devicesrv" mrp="" bldFile="sf/os/devicesrv/group" name="devicesrv"/>                  
      </module>
<module name="">
<unit unitID="AudioEqualizerUtility" mrp="" bldFile="sf/os/mm/devsoundextensions/effectspresets/AudioEqualizerUtility/group" filter="!dfs_build" name="AudioEqualizerUtility"/>
<unit unitID="EnvironmentalReverbUtility" mrp="" bldFile="sf/os/mm/devsoundextensions/effectspresets/EnvironmentalReverbUtility/group" filter="!dfs_build" name="EnvironmentalReverbUtility"/>
<unit unitID="StereoWideningUtility" mrp="" bldFile="sf/os/mm/devsoundextensions/effectspresets/StereoWideningUtility/group" filter="!dfs_build" name="StereoWideningUtility"/>
</module>
<module name="graphics">
        <unit unitID="abs.graphics" mrp="" bldFile="sf/os/graphics/group" name="graphics"/>
        <!-- MattD: graphics/group is missing, as are various subdirs...lets cobble something together... -->
        <unit unitID="abs.graphics.plat" mrp="" bldFile="sf/os/graphics/group/../graphics_plat/group" name="graphics_plat"/>
        <unit unitID="abs.graphics.m3gcoreapi" mrp="" bldFile="sf/os/graphics/group/../graphics_plat/m3g_core_api/group" name="graphics_m3g_api"/>
        <unit unitID="abs.graphics.m3gcore" mrp="" bldFile="sf/os/graphics/group/../m3g/m3gcore11/group" name="graphics_m3g"/>
        <unit unitID="abs.graphics.acceleration_vgi" mrp="" bldFile="sf/os/graphics/group/../graphicsaccelaration/vgi/group" name="graphics_acceleration_vgi"/>
      </module>
<module name="imagingext">
        <unit unitID="imm.imagingext" mrp="" bldFile="sf/os/imagingext/group" name="imagingext"/>
      </module>
<module name="lbs">
        <unit unitID="lodo.lbs" mrp="" bldFile="sf/os/lbs/group" name="lodo.lbs"/>
      </module>
<module name="mm">
				<unit unitID="mm" mrp="" bldFile="sf/os/mm/group" name="mm"/>
			</module>
<module name="osrndtools">
        <unit unitID="tools.osrndtools" mrp="" bldFile="sf/os/osrndtools/group" name="osrndtools"/>
      </module>
<module name="usb">
        <unit unitID="lcdo.usb" mrp="" bldFile="sf/os/usb/group" name="usb"/>
      </module>
<module name="wlan">
        <unit unitID="netdo.wlan" mrp="" bldFile="sf/os/wlan/group" name="wlan"/>
      </module>
<module name="sf_common_tsy">
			<component name="sf_common_tsy">
				<unit unitID="symbian.common_tsy" name="sf_common_tsy" bldFile="sf/os/cellularsrv/telephonyserverplugins/common_tsy/group" mrp="" filter=""/>
			</component>
		</module>
<module name="sf_openvg11">
			<component name="sf_openvg11">
				<unit unitID="symbian.openvg11" name="sf_openvg11" bldFile="\sf\os\graphics\openvg\openvginterface\group\openvg11" mrp="" filter="sf_build"/>
				<unit unitID="symbian.openvg11_KhronosRI" name="sf_openvg11_KhronosRI" bldFile="\sf\os\graphics\openvg\openvgrefimplementation\sfopenvg\group" mrp="" filter="sf_build"/>
			</component>
		</module></layer>
	<layer name="bldfirst_mw_layer">
<module name="classicui">
        <unit unitID="abs.classicui" mrp="" bldFile="sf/mw/classicui/group" name="classicui"/>
      </module>
<module name="gsprofilesrv">
        <unit name="gsprofilesrv" unitID="presdo.gsprofilesrv" bldFile="sf/mw/gsprofilesrv/group" mrp=""/>
      </module></layer>
	<layer name="mw_layer">
<module name="accesssec">
        <unit unitID="netdo.accesssec" mrp="" bldFile="sf/mw/accesssec/group" name="accesssec"/>
      </module>
<module name="appinstall">
        <unit unitID="sedo.appinstall" mrp="" bldFile="sf/mw/appinstall/group" name="appinstall"/>
      </module>
<module name="appsupport">
        <unit unitID="sydo.appsupport" name="appsupport" bldFile="sf/mw/appsupport/group" mrp=""/>
      </module>
<module name="">
<unit unitID="sedo.securitysrv.pkiutilities.Certificates" bldFile="sf/mw/securitysrv/pkiutilities/Certificates/group" mrp="" filter="sf_build" name="sedo_securitysrv_pkiutilities_Certificates"/>
</module>
<module name="btservices">
        <unit unitID="lcdo.btservices" mrp="" bldFile="sf/mw/btservices/group" name="btservices"/>
      </module>
<module name="camerasrv">
        <unit unitID="imm.camerasrv" mrp="" bldFile="sf/mw/camerasrv/group" name="camerasrv"/>
      </module>
<module name="dlnasrv">
        <unit name="dlnasrv" unitID="hcdo.dlnasrv" bldFile="sf/mw/dlnasrv/group" mrp=""/>
      </module>
<module name="drm">
        <unit unitID="sedo.drm" mrp="" bldFile="sf/mw/drm/group" name="drm"/>
      </module>
<module name="hapticsservices">
        <unit unitID="abs.hapticsservices" mrp="" bldFile="sf/mw/hapticsservices/group" name="hapticsservices"/>
      </module>
<module name="helix">
				<unit unitID="helix_stub" mrp="" bldFile="sf/mw/helix/helix_ren/helix_stub/group" filter="sf_build" name="helix_stub"/>
			</module>
<module name="homescreensrv">
        <unit unitID="hs.homescreensrv" mrp="" bldFile="sf/mw/homescreensrv/group" name="homescreensrv"/>
      </module>
<module name="imghandling">
        <unit unitID="imm.imghandling" mrp="" bldFile="sf/mw/imghandling/group" name="imghandling"/>
      </module>
<module name="imsrv">
        <unit unitID="MeCodo.imsrv" mrp="" bldFile="sf/mw/imsrv/group" name="imsrv"/>
      </module>
<module name="inputmethods">
        <unit unitID="abs.inputmethods" mrp="" bldFile="sf/mw/inputmethods/group" name="inputmethods"/>
      </module>
<module name="ipappprotocols">
  		<unit unitID="ipapdo.ipappprotocols" name="ipappprotocols" bldFile="sf/mw/ipappprotocols/group" mrp=""/> 
      </module>
<module name="ipappsrv">
  		<unit unitID="ipasdo.ipappsrv" name="ipappsrv" bldFile="sf/mw/ipappsrv/group" mrp=""/> 
      </module>
<module name="ipconnmgmt">
        <unit unitID="netdo.ipconnmgmt" mrp="" bldFile="sf/mw/ipconnmgmt/group" name="ipconnmgmt"/>
      </module>
<module name="legacypresence">
        <unit unitID="presdo.legacypresence" mrp="" bldFile="sf/mw/legacypresence/group" name="legacypresence"/>
      </module>
<module name="locationsrv">
        <unit unitID="lodo.locationsrv" mrp="" bldFile="sf/mw/locationsrv/group" name="locationsrv"/>
      </module>
<module name="mds">
        <unit unitID="imm.mds" mrp="" bldFile="sf/mw/mds/group" name="mds"/>
      </module>
<module name="messagingmw">
        <unit unitID="Medo.messagingmw" mrp="" bldFile="sf/mw/messagingmw/group" name="messagingmw"/>
      </module>
<module name="metadatasrv">
        <unit unitID="imm.metadatasrv" mrp="" bldFile="sf/mw/metadatasrv/group" name="metadatasrv"/>
      </module>
<module name="mmappfw">
				<unit unitID="mmappfw" mrp="" bldFile="sf/mw/mmappfw/group" name="mmappfw"/>
			</module>
<module name="mmmw">
				<unit unitID="mmmw" mrp="" bldFile="sf/mw/mmmw/group" name="mmmw"/>
				<!-- MattD 20100205 - This stub is needed for metadatautility (see Bug 1529) -->
				<unit unitID="mmmw_3GPExtParserLib_stub" mrp="" bldFile="sf/mw/mmmw/mmserv/metadatautility/3GPExtParserLib_stub/group" name="mmmw_3GPExtParserLib_stub"/>
			</module>
<module name="mmuifw">
        <unit unitID="uxdo.mmuifw" mrp="" bldFile="sf/mw/mmuifw/group" name="mmuifw"/>
      </module>
<module name="netprotocols">
	    <unit unitID="browsing_domain.netprotocols" mrp="" bldFile="sf/mw/netprotocols/group" name="netprotocols"/>
      </module>
<module name="opensrv">
        <unit unitID="MeCodo.opensrv" mrp="" bldFile="sf/mw/opensrv/group" name="opensrv"/>
      </module>
<module name="phonesrv">
	      <unit name="phonesrv" unitID="tedo.phonesrv" bldFile="sf/mw/phonesrv/group" mrp=""/>
      </module>
<module name="platformtools">
        <unit unitID="tools.platformtools" mrp="" bldFile="sf/mw/platformtools/group" name="platformtools"/>
      </module>
<module name="ptihangulcore">
        <unit unitID="abs.ptihangulcore" mrp="" bldFile="sf/mw/ptihangulcore/group" name="ptihangulcore"/>
      </module>
<module name="ptikoreanqwertycore">
        <unit unitID="abs.ptikoreanqwertycore" mrp="" bldFile="sf/mw/ptikoreanqwertycore/group" name="ptikoreanqwertycore"/>
      </module>
<module name="qt">
        <unit unitID="qtdo.qt" mrp="" bldFile="sf/mw/qt" name="qt"/>
      </module>
<module name="remoteconn">
        <unit name="remoteconn" unitID="sydo.remoteconn" bldFile="sf/mw/remoteconn/group" mrp=""/>
      </module>
<module name="remotemgmt">
        <unit unitID="spdo.remotemgmt" mrp="" bldFile="sf/mw/remotemgmt/group" name="remotemgmt"/>
      </module>
<module name="remotestorage">
        <unit unitID="presdo.remotestorage" mrp="" bldFile="sf/mw/remotestorage/group" name="remotestorage"/>
      </module>
<module name="securitysrv">
        <unit name="securitysrv" unitID="sedo.securitysrv" bldFile="sf/mw/securitysrv/group" mrp=""/>
      </module>
<module name="serviceapi">                             
<unit name="serviceapi" unitID="sapido.serviceapi" bldFile="sf/mw/serviceapi/group" mrp=""/>
</module>
<module name="serviceapifw">                             
<unit name="serviceapifw" unitID="sapido.serviceapifw" bldFile="sf/mw/serviceapifw/group" mrp=""/>
</module>
<module name="shortlinkconn">
        <unit unitID="lcdo.shortlinkconn" mrp="" bldFile="sf/mw/shortlinkconn/group" name="shortlinkconn"/>
      </module>
<module name="upnp">                             
<unit name="upnp" unitID="mrtdo.upnp" bldFile="sf/mw/srvdiscovery/upnp/group" mrp=""/>
</module>
<module name="svgt">
        <unit unitID="abs.svgt" mrp="" bldFile="sf/mw/svgt/group" name="svgt"/>
      </module>
<module name="uiaccelerator">
        <unit unitID="abs.uiaccelerator" mrp="" bldFile="sf/mw/uiaccelerator/group" name="uiaccelerator"/>
      </module>
<module name="uiresources">
        <unit unitID="abs.uiresources" mrp="" bldFile="sf/mw/uiresources/group" name="uiresources"/>
        <unit unitID="abs.uiresources_nvgrender" mrp="" bldFile="sf/mw/uiresources/uigraphics/nvgrenderstage/group" name="uiresources_nvgrender"/>        
      </module>
<module name="usbservices">
        <unit unitID="lcdo.usbservices" mrp="" bldFile="sf/mw/usbservices/group" name="usbservices"/>
        <!-- MattD: I really need to FCL the component to Add in a couple of null bld.inf files, but I'll push it a bit further by doing this -->
        <unit unitID="more.usbservices" mrp="" bldFile="sf/mw/usbservices/usbservices_plat/group" name="usbservices_API"/>
      </module>
<module name="videoutils">
        <unit unitID="vado.videoutils" mrp="" bldFile="sf/mw/videoutils/group" name="videoutils"/>
      </module>
<module name="vpnclient"> 
     	<unit unitID="netdo.vpnclient" mrp="" bldFile="sf/mw/vpnclient/group" filter="!oem_build" name="vpnclient"/>
     </module>
<module name="web">
	    <unit unitID="browsing_domain.web" mrp="" bldFile="sf/mw/web/group" name="web"/>
      </module>
<module name="websrv">
        <unit unitID="WSDo.websrv" mrp="" bldFile="sf/mw/websrv/group" name="websrv"/>        
      </module>
<module name="wirelessacc">
        <unit unitID="netdo.wirelessacc" mrp="" bldFile="sf/mw/wirelessacc/group" name="wirelessacc"/>
      </module>
<module name="ossrv">                             
<unit name="ossrv" unitID="mrtdo.ossrv" bldFile="sf/os/ossrv/group" mrp=""/>
</module>
<module name="textandloc">
        <unit unitID="abs.textandloc" mrp="" bldFile="sf/os/textandloc/group" name="textandloc"/>
      </module>
<module name="xmlsrv">
        <unit unitID="WSDo.xmlsrv" mrp="" bldFile="sf/os/xmlsrv/group" name="xmlsrv"/>
      </module></layer>
	<layer name="bldfirst_app_layer">
<module name="contacts">
        <unit unitID="contacts" mrp="" bldFile="sf/app/contacts/group" name="contacts"/>
      </module></layer>
	<layer name="app_layer">
<module name="oemrndtools">
        <unit unitID="tools.oemrndtools" mrp="" bldFile="ext/tools/oemrndtools/group" name="oemrndtools"/>
      </module>
<module name="camera">
        <unit unitID="imm.camera" mrp="" bldFile="sf/app/camera/group" name="camera"/>
        <unit unitID="imm.camera.help" mrp="" bldFile="sf/app/camera/camerauis/cameraapp/help/group" name="camera_help"/>
      </module>
<module name="commonemail">
        <unit unitID="EDo.commonemail" mrp="" bldFile="sf/app/commonemail/group" name="commonemail"/>
      </module>
<module name="conntools">
        <unit unitID="netdo.conntools" mrp="" bldFile="sf/app/conntools/group" name="conntools"/>
      </module>
<module name="contentcontrol">
        <unit unitID="spdo.contentcontrol" mrp="" bldFile="sf/app/contentcontrol/group" name="contentcontrol"/>
      </module>
<module name="conversations">
        <unit unitID="MeCodo.conversations" mrp="" bldFile="sf/app/conversations/group" name="conversations"/>
      </module>
<module name="devicecontrol">
        <unit unitID="spdo.devicecontrol" mrp="" bldFile="sf/app/devicecontrol/group" name="devicecontrol"/>
      </module>
<module name="dictionary">
        <unit unitID="abs.dictionary" mrp="" bldFile="sf/app/dictionary/group" name="dictionary"/>
      </module>
<module name="files">
        <unit name="files" unitID="presdo.files" bldFile="sf/app/files/group" mrp=""/>
      </module>
<module name="graphicsuis">
        <unit unitID="abs.graphicsuis" mrp="" bldFile="sf/app/graphicsuis/group" name="graphicsuis"/>
      </module>
<module name="helps">
        <unit unitID="abs.helps" mrp="" bldFile="sf/app/helps/group" name="helps"/>
      </module>
<module name="homescreen">
        <unit unitID="abs.homescreen" mrp="" bldFile="sf/app/homescreen/group" name="homescreen"/>
      </module>
<module name="im">
        <unit unitID="impp.im" mrp="" bldFile="sf/app/im/group" name="im"/>
      </module>
<module name="iptelephony">
        <unit name="iptelephony" unitID="te.iptelephony" bldFile="sf/app/iptelephony/group" mrp=""/>
      </module>
<module name="jrt">
<unit unitID="jrt.jrt.jrt_plat" mrp="" bldFile="sf/app/jrt/jrt_plat/group" filter="sf_build" name="jrt_jrt_plat"/>
<unit unitID="jrt.jrt.java_stubs" mrp="" bldFile="sf/app/jrt/java_stubs/group" filter="sf_build" name="jrt_jrt_stubs"/></module>
<module name="location">
        <unit unitID="lodo.location" mrp="" bldFile="sf/app/location/group" name="location"/>
      </module>
<module name="messaging">
        <unit unitID="Medo.messaging" mrp="" bldFile="sf/app/messaging/group" name="messaging"/>
      </module>
<module name="mmsharinguis">
  		<unit unitID="msdo.mmsharinguis" name="mmsharinguis" bldFile="sf/app/mmsharinguis/group" mrp=""/> 
      </module>
<module name="musicplayer">
				<unit unitID="musicplayer" mrp="" bldFile="sf/app/musicplayer/group" name="musicplayer"/>
			</module>
<module name="organizer">
        <unit unitID="orgdo.organizer" mrp="" bldFile="sf/app/organizer/group" name="organizer"/>
      </module>
<module name="phone">
        <unit name="phone" unitID="tedo.phone" bldFile="sf/app/phone/group" mrp=""/>
      </module>
<module name="photos">
        <unit unitID="uxdo.photos" mrp="" bldFile="sf/app/photos/group" name="photos"/>
      </module>
<module name="printing">
        <unit unitID="lcdo.printing" mrp="" bldFile="sf/app/printing/group" name="printing"/>
      </module>
<module name="profile">
        <unit name="profile" unitID="presdo.profile" bldFile="sf/app/profile/group" mrp=""/>
      </module>
<module name="radio">
        <unit unitID="vado.radio" mrp="" bldFile="sf/app/radio/group" name="radio"/>
      </module>
<module name="rndtools">
        <unit unitID="tools.rndtools" mrp="" bldFile="sf/app/rndtools/group" name="rndtools"/>
      </module>
<module name="screensaver">
        <unit unitID="abs.screensaver" mrp="" bldFile="sf/app/screensaver/group" name="screensaver"/>
      </module>
<module name="settingsuis">
      <unit name="settingsuis" unitID="presdo.settingsuis" bldFile="sf/app/settingsuis/group" mrp=""/>
      </module>
<module name="speechsrv">
        <unit unitID="MuiDo.speechsrv" mrp="" bldFile="sf/app/speechsrv/group" name="speechsrv"/>
      </module>
<module name="utils">
        <unit unitID="orgdo.utils" mrp="" bldFile="sf/app/utils/group" name="utils"/>
      </module>
<module name="videoplayer">
        <unit unitID="vado.videoplayer" mrp="" bldFile="sf/app/videoplayer/group" name="videoplayer"/>
      </module>
<module name="videotelephony">
        <unit name="videotelephony_plat" unitID="tedo.videotelephony_plat" bldFile="sf/app/videotelephony/videotelephony_plat/group" mrp=""/>
        <unit name="vtprotocolsstub" unitID="tedo.vtprotocolsstub" bldFile="sf/app/videotelephony/vtprotocolsstub/group" mrp="" filter="sf_build"/>  
        <unit name="DisplaySink" unitID="tedo.DisplaySink" bldFile="sf/app/videotelephony/vtprotocolplugins/DisplaySink/group" mrp=""/> 
        <unit name="VideoSource" unitID="tedo.VideoSource" bldFile="sf/app/videotelephony/vtprotocolplugins/VideoSource/group" mrp=""/>
        <unit name="videoteleng" unitID="tedo.videoteleng" bldFile="sf/app/videotelephony/vtengines/videoteleng/Group" mrp=""/>  
        <unit name="videotelui" unitID="tedo.videotelui" bldFile="sf/app/videotelephony/vtuis/videotelui/group" mrp=""/> 
	<unit name="vtmediatorplugin" unitID="tedo.vtmediatorplugin" bldFile="sf/app/videotelephony/vtengines/vtmediatorplugin/group" mrp=""/>
      </module>
<module name="voicerec">
				<unit unitID="voicerec" mrp="" bldFile="sf/app/voicerec/group" name="voicerec"/>
			</module>
<module name="webuis">
	    <unit unitID="browsing_domain.webuis" mrp="" bldFile="sf/app/webuis/group" name="webuis"/>
      </module>
<module name="locfiles">
				<unit unitID="platform.locfiles" mrp="" bldFile="sf/os/deviceplatformrelease/locfiles/group" filter="" name="locfiles"/>
				<unit unitID="platform.locfiles.set1" mrp="" bldFile="sf/os/deviceplatformrelease/locfiles/group/set1" filter="" name="locfiles_set1"/>
				<unit unitID="platform.locfiles.set2" mrp="" bldFile="sf/os/deviceplatformrelease/locfiles/group/set2" filter="" name="locfiles_set2"/>
				<unit unitID="platform.locfiles.set3" mrp="" bldFile="sf/os/deviceplatformrelease/locfiles/group/set3" filter="" name="locfiles_set3"/>
				<unit unitID="platform.locfiles.set4" mrp="" bldFile="sf/os/deviceplatformrelease/locfiles/group/set4" filter="" name="locfiles_set4"/>
				<unit unitID="platform.locfiles.set5" mrp="" bldFile="sf/os/deviceplatformrelease/locfiles/group/set5" filter="" name="locfiles_set5"/>
				<unit unitID="platform.locfiles.set6" mrp="" bldFile="sf/os/deviceplatformrelease/locfiles/group/set6" filter="" name="locfiles_set6"/>
				<unit unitID="platform.locfiles.set7" mrp="" bldFile="sf/os/deviceplatformrelease/locfiles/group/set7" filter="" name="locfiles_set7"/>
				<unit unitID="platform.locfiles.set8" mrp="" bldFile="sf/os/deviceplatformrelease/locfiles/group/set8" filter="" name="locfiles_set8"/>
				<unit unitID="platform.locfiles.set9" mrp="" bldFile="sf/os/deviceplatformrelease/locfiles/group/set9" filter="" name="locfiles_set9"/>
				<unit unitID="platform.locfiles.set10" mrp="" bldFile="sf/os/deviceplatformrelease/locfiles/group/set10" filter="" name="locfiles_set10"/>
				<unit unitID="platform.locfiles.set11" mrp="" bldFile="sf/os/deviceplatformrelease/locfiles/group/set11" filter="" name="locfiles_set11"/>
				<unit unitID="platform.locfiles.set12" mrp="" bldFile="sf/os/deviceplatformrelease/locfiles/group/set12" filter="" name="locfiles_set12"/>
				<unit unitID="platform.locfiles.set13" mrp="" bldFile="sf/os/deviceplatformrelease/locfiles/group/set13" filter="" name="locfiles_set13"/>
				<unit unitID="platform.locfiles.set14" mrp="" bldFile="sf/os/deviceplatformrelease/locfiles/group/set14" filter="" name="locfiles_set14"/>
				<unit unitID="platform.locfiles.set15" mrp="" bldFile="sf/os/deviceplatformrelease/locfiles/group/set15" filter="" name="locfiles_set15"/>
				<unit unitID="platform.locfiles.set16" mrp="" bldFile="sf/os/deviceplatformrelease/locfiles/group/set16" filter="" name="locfiles_set16"/>
      </module>
<module name="helps_loc2">
        <unit unitID="platform.helps_loc2" mrp="" bldFile="sf/os/deviceplatformrelease/helps_loc2/group" name="helps_loc2"/>
      </module>
    </layer>
	<layer name="tools_layer">
<module name="qtconf">
        <unit unitID="qtdo.qt.qtconf" mrp="" bldFile="sf/mw/qt/group" name="qtconf"/>
      </module>
<module name="uitools">
        <unit unitID="abs.uitools" mrp="" bldFile="sf/mw/uitools/group" name="uitools"/>
      </module>
<module name="homescreentools">
        <unit unitID="hsdo.themeinstaller" mrp="" bldFile="sf/tools/homescreentools/themeinstaller/group" name="themeinstaller"/>
<unit unitID="abs.homescreentools" mrp="" bldFile="sf/tools/homescreentools/group" name="homescreentools"/>
        <unit unitID="hsdo.widgettools" mrp="" bldFile="sf/tools/homescreentools/widgettools/group" name="widgettools"/>
      </module>
<module name="buildplatforms">
    <unit unitID="sf_tools_buildplatforms" name="buildplatforms" bldFile="\sf\tools\buildplatforms\group" mrp=""/>
</module>
<module name="swconfigtools">
        <unit name="swconfigtools" unitID="sydo.swconfigtools" bldFile="sf/tools/swconfigtools/group" mrp=""/>
      </module></layer>
	<layer name="stubs_layer">
<module name="audiostubs">
				<unit unitID="audiostubs" mrp="" bldFile="sf/adaptation/stubs/audiostubs/group" name="audiostubs"/>
			</module>
<module name="drm_stubs">
        <unit name="drm_stubs" unitID="sedo.drm_stubs" bldFile="sf/adaptation/stubs/drm_stubs/group" mrp=""/>
      </module>
<module name="ocrsrv_stub">
        <unit unitID="abs.ocrsrv_stub" mrp="" bldFile="sf/adaptation/stubs/ocrsrv_stub/group" filter="!dfs_build" name="ocrsrv_stub"/>
      </module>
<module name="omasuplasnconverterstubimpl">
        <unit unitID="lodo.omasuplasnconverterstubimpl" mrp="" bldFile="sf/adaptation/stubs/omasuplasnconverterstubimpl/group" filter="!dfs_build" name="omasuplasnconverterstubimpl"/>
      </module>
<module name="posmsgpluginreferenceimpl">
        <unit unitID="lodo.posmsgpluginreferenceimpl" mrp="" bldFile="sf/adaptation/stubs/posmsgpluginreferenceimpl/group" name="posmsgpluginreferenceimpl"/>
      </module>
<module name="power_save_display_mode_stub">
        <unit unitID="abs.power_save_display_mode_stub" mrp="" bldFile="sf/adaptation/stubs/power_save_display_mode_stub/group" name="power_save_display_mode_stub"/>
      </module>
<module name="systemswstubs">
  	<unit name="systemswstubs" unitID="sydo.systemswstubs" bldFile="sf/adaptation/stubs/systemswstubs/group" mrp=""/>
      </module>
<module name="tactileclickplugin_stub">
        <unit unitID="abs.tactileclickplugin_stub" mrp="" bldFile="sf/adaptation/stubs/tactileclickplugin_stub/group" name="tactileclickplugin_stub"/>
      </module>
<module name="wlanhwinit_stub">
        <unit unitID="netdo.wlanhwinit_stub" mrp="" bldFile="sf/adaptation/stubs/wlanhwinit_stub/group" name="wlanhwinit_stub"/>
      </module>
<module name="sf_licenseetsystub">
			<component name="sf_licenseetsystub">
				<unit unitID="symbian.licenseetsystub" name="sf_licenseetsystub" bldFile="sf/os/cellularsrv/telephonyserverplugins/licenseetsystub/group" mrp="" filter=""/>
			</component>
		</module></layer>
<layer name="unit_test_layer">
      <module name="camera_unit_tests">
      </module>
<module name="camerasrv_unit_tests">
      </module>
<module name="imagehandling_unit_tests">
    </module>
<module name="mds_unit_tests">
      </module>
<module name="metadatasrv_unit_tests">
      </module></layer>
</systemModel>
  <build>
    <option name="KEEPGOING" abldOption="-keepgoing" description="Causes make to keepgoing on errors" enable="Y"/>
<!--    <option name="SAVESPACE" abldOption="-savespace" description="Causes the removal of intermediate files" enable="Y"/> -->
    <target name="WINS" abldTarget="wins" description="MSVC Compiler"/>
    <target name="WINS_REL" abldTarget="wins urel" description="MSVC Compiler"/>
    <target name="WINS_DEB" abldTarget="wins udeb" description="MSVC Compiler"/>
    <target name="WINSCW" abldTarget="winscw" description="CodeWarrior Compiler"/>
    <target name="WINSCW_REL" abldTarget="winscw urel" description="CodeWarrior Compiler"/>