<?xml version="1.0"?>
<!DOCTYPE SystemDefinition [

 <!ELEMENT SystemDefinition (systemModel?, build?)>
 <!ATTLIST SystemDefinition
  name CDATA #REQUIRED
  schema CDATA #REQUIRED>
 <!ELEMENT systemModel (layer+)>
 <!ELEMENT layer (logicalset* | module*)*>
 <!ATTLIST layer
  name CDATA #REQUIRED
  levels CDATA #IMPLIED
  span CDATA #IMPLIED>
 <!ELEMENT logicalset (logicalsubset* | module* | unit* | package* | prebuilt*)*>
 <!ATTLIST logicalset 
  name CDATA #REQUIRED
  levels CDATA #IMPLIED  
  span CDATA #IMPLIED
  level CDATA #IMPLIED>
 <!ELEMENT logicalsubset (module* | unit* | package* | prebuilt*)*>
 <!ATTLIST logicalsubset name CDATA #REQUIRED>
 <!ELEMENT module (component* | unit* | package* | prebuilt*)*>
 <!ATTLIST module
  name CDATA #REQUIRED
  level CDATA #IMPLIED>
 <!ELEMENT component (unit* | package* | prebuilt*)*>
 <!ATTLIST component name CDATA #REQUIRED>
 <!ELEMENT unit EMPTY>
 <!ATTLIST unit
  unitID ID #REQUIRED
  name CDATA #REQUIRED
  mrp CDATA #REQUIRED
  filter CDATA #IMPLIED
  bldFile CDATA #REQUIRED
  priority CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT package EMPTY>
 <!ATTLIST package
  name CDATA #REQUIRED
  mrp CDATA #REQUIRED
  filter CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT prebuilt EMPTY>
 <!ATTLIST prebuilt
  name CDATA #REQUIRED
  version CDATA #REQUIRED
  late (Y|N) #IMPLIED
  filter CDATA #IMPLIED
  contract CDATA #IMPLIED>
 <!ELEMENT build (option* | target+ | targetList+ | unitList+ | configuration+)*>
 <!ELEMENT unitList (unitRef+)>
 <!ATTLIST unitList
  name ID #REQUIRED
  description CDATA #REQUIRED>
 <!ELEMENT unitRef EMPTY>
 <!ATTLIST unitRef unit IDREF #REQUIRED>
 <!ELEMENT targetList EMPTY>
 <!ATTLIST targetList
  name ID #REQUIRED
  description CDATA #REQUIRED
  target IDREFS #REQUIRED>
 <!ELEMENT target EMPTY>
 <!ATTLIST target
  name ID #REQUIRED
  abldTarget CDATA #REQUIRED
  description CDATA #REQUIRED>
 <!ELEMENT option EMPTY>
 <!ATTLIST option
  name ID #REQUIRED
  abldOption CDATA #REQUIRED
  description CDATA #REQUIRED
  enable (Y | N | y | n) #REQUIRED>
 <!ELEMENT configuration (unitListRef+ | layerRef+ | task+)*>
 <!ATTLIST configuration
  name ID #REQUIRED
  description CDATA #REQUIRED
  filter CDATA #REQUIRED>
 <!ELEMENT task ( unitListRef* , (buildLayer | specialInstructions))>
 <!ELEMENT unitListRef EMPTY>
 <!ATTLIST unitListRef unitList IDREF #REQUIRED>
 <!ELEMENT layerRef EMPTY>
 <!ATTLIST layerRef layerName CDATA #REQUIRED>
 <!ELEMENT buildLayer EMPTY>
 <!ATTLIST buildLayer
  command CDATA #REQUIRED
  targetList IDREFS #IMPLIED
  unitParallel (Y | N | y | n) #REQUIRED
  targetParallel (Y | N | y | n) #IMPLIED>
 <!ELEMENT specialInstructions EMPTY>
 <!ATTLIST specialInstructions
  name CDATA #REQUIRED
  cwd CDATA #REQUIRED
  command CDATA #REQUIRED>
]>
<SystemDefinition name="S60_SystemBuild" schema="1.4.0">
<systemModel>
<layer name="src">
<module name="hlpmodel">
<component name="hlpmodel">
<unit unitID="S60_hlpmodel" name="hlpmodel" bldFile="\src\common\generic\app-services\hlpmodel\group" mrp=""/>
</component>
</module>
</layer>
<layer name="extra">
	<module name="WlanEapSettingsUi_ccx">
		<component name="WlanEapSettingsUi_ccx">
			<unit unitID="s60_mw_networking_networkingutilities_WlanEapSettingsUi_group_ccx" name="WlanEapSettingsUi_ccx" bldFile="\sf\mw\accesssec\wlansecuritysettings\wlaneapsettingsui\group\ccx" mrp=""/>
		</component>
	</module>
</layer>
</systemModel>

  <build>
    <option name="KEEPGOING" abldOption="-keepgoing" description="Causes make to keepgoing on errors" enable="Y"/>
<!--    <option name="SAVESPACE" abldOption="-savespace" description="Causes the removal of intermediate files" enable="Y"/> -->
    <target name="WINS" abldTarget="wins" description="MSVC Compiler"/>
    <target name="WINS_REL" abldTarget="wins urel" description="MSVC Compiler"/>
    <target name="WINS_DEB" abldTarget="wins udeb" description="MSVC Compiler"/>
    <target name="WINSCW" abldTarget="winscw" description="CodeWarrior Compiler"/>
    <target name="WINSCW_REL" abldTarget="winscw urel" description="CodeWarrior Compiler"/>
    <target name="WINSCW_DEB" abldTarget="winscw udeb" description="CodeWarrior Compiler"/>
    <target name="TOOLS" abldTarget="tools" description="MSVC Compiler for Tools"/>
    <target name="TOOLS_REL" abldTarget="tools rel" description="MSVC Compiler for Tools Release mode only"/>
    <target name="ARMV5" abldTarget="armv5" description="RVCT Compiler"/>
    <target name="ARMV5_REL" abldTarget="armv5 urel" description="RVCT Compiler"/>
    <target name="ARMV5_DEB" abldTarget="armv5 udeb" description="RVCT Compiler"/>

    <!-- Aditional Targets -->
    <target name="CWTOOLS" abldTarget="cwtools" description="CodeWarrior Compiler for Tools"/> <!-- Not supported -->
    <target name="CWTOOLS_REL" abldTarget="cwtools rel" description="CodeWarrior Compiler for Tools Release mode only"/> <!-- Not supported -->
    
    <targetList name="default" description="Main Targets" target="WINSCW ARMV5"/>
    <targetList name="default_winscw" description="Main Targets" target="WINSCW"/>
    <targetList name="default_armv5" description="Main Targets" target="ARMV5"/>
    <targetList name="default_rel" description="Main Targets for rel" target="WINSCW_REL ARMV5_REL"/>
    <targetList name="default_deb" description="Main Targets for deb" target="WINSCW_DEB ARMV5_DEB"/>
    <targetList name="default_debrel" description="Main Targets for WINSCW deb and ARMV5 urel" target="WINSCW_DEB ARMV5_REL"/>
    <targetList name="default_tools" description="tools Targets" target="TOOLS"/>
    <targetList name="tools_rel" description="tools Release Targets" target="TOOLS_REL"/>
    <targetList name="cwtools" description="cwtools Targets" target="CWTOOLS"/>
    <targetList name="cwtools_rel" description="cwtools Release Targets" target="CWTOOLS_REL"/>
  

  	<configuration name="S60_bldmefirst" description="S60 bldmefirst part" filter="S60_5_0">
      <unitListRef unitList="S60_BLDMEFIRST_EXPORT_OEM"/>

			<!-- export platform_paths.hrh -->
      <task><specialInstructions name="platform_path_definitions_api" cwd="\sf\os\devicesrv\devicesrv_pub\platform_path_definitions_api\group" command="bldmake bldfiles -k"/></task> 
      <task><specialInstructions name="platform_path_definitions_api" cwd="\sf\os\devicesrv\devicesrv_pub\platform_path_definitions_api\group" command="abld export -k"/></task> 

			<!-- export platform security headers -->
      <task><specialInstructions name="common_platform_security_definitions_api" cwd="\sf\os\devicesrv\devicesrv_pub\common_platform_security_definitions_api\group" command="bldmake bldfiles -k"/></task> 
      <task><specialInstructions name="common_platform_security_definitions_api" cwd="\sf\os\devicesrv\devicesrv_pub\common_platform_security_definitions_api\group" command="abld export -k"/></task> 

			<!-- export common headers -->
      <task><specialInstructions name="export_commonengine_platform_paths" cwd="\sf\os\devicesrv\commonservices\commonengine\group" command="bldmake bldfiles -k"/></task> 
      <task><specialInstructions name="export_commonengine_platform_paths" cwd="\sf\os\devicesrv\commonservices\commonengine\group" command="abld export -k"/></task> 

			<!-- export Browser_platform_variant.hrh -->
      <task><specialInstructions name="browser_platform_api" cwd="\sf\mw\web\web_plat\browser_platform_api\group" command="bldmake bldfiles -k"/></task> 
      <task><specialInstructions name="browser_platform_api" cwd="\sf\mw\web\web_plat\browser_platform_api\group" command="abld export -k"/></task> 

  		<task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="N"/></task>

			<!-- touch extracted bitmaps and icons  -->
      <task><specialInstructions name="touch_bitmaps" cwd="\" command="toucher.exe \sf\mw\uiresources\uigraphics\Bitmaps2"/></task> 
      <task><specialInstructions name="touch_bitmaps" cwd="\" command="toucher.exe \epoc32\s60\bitmaps"/></task> 
      <task><specialInstructions name="touch_icons" cwd="\" command="toucher.exe \sf\mw\uiresources\uigraphics\Icons"/></task> 
      <task><specialInstructions name="touch_icons" cwd="\" command="toucher.exe \epoc32\s60\icons"/></task> 

			<!-- copy s60 makefile templates from s60\tools\makefile_templates to \epoc32\tools\makefile_templates. makefile templates are needed in current location before 'bldmake bldfiles' has launched -->
      <task><specialInstructions name="copy_makefile" cwd="\" command="for /R \sf\tools\makefile_templates\ %a in (*) do xcopy /Y /R %a \epoc32\tools\makefile_templates\s60\"/></task> 
      <task><specialInstructions name="copy_makefile" cwd="\" command="erase /F \epoc32\tools\makefile_templates\s60\Distribution.Policy.S60"/></task>
      
<!-- crete empty folders to get emulator work -->
      <task><specialInstructions name="create_folder_emu" cwd="\" command="md \epoc32\wins\D"/></task> 
      <task><specialInstructions name="create_folder_emu" cwd="\" command="md \epoc32\winscw\D"/></task> 
  	</configuration>

  	<configuration name="S60_bldmefirst_sf" description="S60 bldmefirst part" filter="S60_5_0">
      <unitListRef unitList="S60_BLDMEFIRST_EXPORT"/>

			<!-- export platform_paths.hrh -->
      <task><specialInstructions name="platform_path_definitions_api" cwd="\sf\os\devicesrv\devicesrv_pub\platform_path_definitions_api\group" command="bldmake bldfiles -k"/></task> 
      <task><specialInstructions name="platform_path_definitions_api" cwd="\sf\os\devicesrv\devicesrv_pub\platform_path_definitions_api\group" command="abld export -k"/></task> 

			<!-- export platform security headers -->
      <task><specialInstructions name="common_platform_security_definitions_api" cwd="\sf\os\devicesrv\devicesrv_pub\common_platform_security_definitions_api\group" command="bldmake bldfiles -k"/></task> 
      <task><specialInstructions name="common_platform_security_definitions_api" cwd="\sf\os\devicesrv\devicesrv_pub\common_platform_security_definitions_api\group" command="abld export -k"/></task> 

			<!-- export common headers -->
      <task><specialInstructions name="export_commonengine_platform_paths" cwd="\sf\os\devicesrv\commonservices\commonengine\group" command="bldmake bldfiles -k"/></task> 
      <task><specialInstructions name="export_commonengine_platform_paths" cwd="\sf\os\devicesrv\commonservices\commonengine\group" command="abld export -k"/></task> 

			<!-- export Browser_platform_variant.hrh -->
      <task><specialInstructions name="browser_platform_api" cwd="\sf\mw\web\web_plat\browser_platform_api\group" command="bldmake bldfiles -k"/></task> 
      <task><specialInstructions name="browser_platform_api" cwd="\sf\mw\web\web_plat\browser_platform_api\group" command="abld export -k"/></task> 

  		<task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="N"/></task>

			<!-- touch extracted bitmaps and icons  -->
      <task><specialInstructions name="touch_bitmaps" cwd="\" command="toucher.exe \sf\mw\uiresources\uigraphics\Bitmaps2"/></task> 
      <task><specialInstructions name="touch_bitmaps" cwd="\" command="toucher.exe \epoc32\s60\bitmaps"/></task> 
      <task><specialInstructions name="touch_icons" cwd="\" command="toucher.exe \sf\mw\uiresources\uigraphics\Icons"/></task> 
      <task><specialInstructions name="touch_icons" cwd="\" command="toucher.exe \epoc32\s60\icons"/></task> 

			<!-- copy s60 makefile templates from s60\tools\makefile_templates to \epoc32\tools\makefile_templates. makefile templates are needed in current location before 'bldmake bldfiles' has launched -->
      <task><specialInstructions name="copy_makefile" cwd="\" command="for /R \sf\tools\makefile_templates\ %a in (*) do xcopy /Y /R %a \epoc32\tools\makefile_templates\s60\"/></task> 
      <task><specialInstructions name="copy_makefile" cwd="\" command="erase /F \epoc32\tools\makefile_templates\s60\Distribution.Policy.S60"/></task>
      
<!-- crete empty folders to get emulator work -->
      <task><specialInstructions name="create_folder_emu" cwd="\" command="md \epoc32\wins\D"/></task> 
      <task><specialInstructions name="create_folder_emu" cwd="\" command="md \epoc32\winscw\D"/></task> 
  	</configuration>
  
   	<configuration name="S60_bldmelast" description="S60 bldmelast part" filter="S60_5_0,western">
      <unitListRef unitList="S60_BLDVARIANT"/>   		
   		<unitListRef unitList="S60_REGIONALVARIANT"/>

<!-- for target arm9e -->
      <task><specialInstructions name="EAacPlusCodecPlugin" cwd="\sf\os\mm\audio\ARM_CMMF_codecs\EAacPlusCodecPlugin\Group" command="bldmake bldfiles -k"/></task> 
      <task><specialInstructions name="EAacPlusCodecPlugin" cwd="\sf\os\mm\audio\ARM_CMMF_codecs\EAacPlusCodecPlugin\Group" command="abld build arm9e -k"/></task> 

<!--new configuration tool cenrep generation western --> 
    <task><specialInstructions name="cenrep_generation" cwd="\epoc32\tools" command="call cli_build.cmd -master_conf s60 -impl \epoc32\rom\config\confml_data\s60 -confml \epoc32\rom\config\confml_data\s60 -ignore_errors"/></task> 

<!-- do what for regional variant that those can be zipped from bldmelast build log file -->
  		<task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
  		<task><buildLayer command="abld makefile" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
  		<task><buildLayer command="abld -what build" targetList="default" unitParallel="Y" targetParallel="Y"/></task>

  	</configuration>

   	<configuration name="S60_bldmelast_sf" description="S60 bldmelast part" filter="S60_5_0,western">
      <unitListRef unitList="S60_BLDVARIANT_SF"/>   		
   		<unitListRef unitList="S60_REGIONALVARIANT"/>

<!-- for target arm9e -->
<!--
      <task><specialInstructions name="EAacPlusCodecPlugin" cwd="\sf\os\mm\audio\ARM_CMMF_codecs\EAacPlusCodecPlugin\Group" command="bldmake bldfiles -k"/></task> 
      <task><specialInstructions name="EAacPlusCodecPlugin" cwd="\sf\os\mm\audio\ARM_CMMF_codecs\EAacPlusCodecPlugin\Group" command="abld build arm9e -k"/></task> 
-->
<!--new configuration tool cenrep generation western --> 
    <task><specialInstructions name="cenrep_generation" cwd="\epoc32\tools" command="call cli_build.cmd -master_conf s60 -impl \epoc32\rom\config\confml_data\s60 -confml \epoc32\rom\config\confml_data\s60 -ignore_errors"/></task> 

<!-- do what for regional variant that those can be zipped from bldmelast build log file -->
  		<task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
  		<task><buildLayer command="abld makefile" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
  		<task><buildLayer command="abld -what build" targetList="default" unitParallel="Y" targetParallel="Y"/></task>

  	</configuration>

   	<configuration name="S60_variant_china" description="S60 chinese regional variant" filter="S60_5_0,china">
      <unitListRef unitList="S60_BLDVARIANT"/>
      <unitListRef unitList="S60_REGIONALVARIANT"/>

<!-- do what for regional variant that those can be zipped from bldmelast build log file -->
  		<task><buildLayer command="toucher.exe ..\.." unitParallel="Y"/></task>
  		<task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="N"/></task>
      <task><specialInstructions name="clean_version" cwd="\sf\os\deviceplatformrelease\Version\group" command="abld cleanexport -k"/></task> 
<!-- this is not a mistake, bldmake bldfiles and exports have to do twice because of changes in bldvariant.hrh -->
  		<task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="N"/></task>
      <task><buildLayer command="abld makefile" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld resource" targetList="default" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld library" targetList="default" unitParallel="Y" targetParallel="N"/></task>
      <task><buildLayer command="abld target" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld final" targetList="default" unitParallel="Y" targetParallel="N"/></task>
      <task><buildLayer command="abld -what build" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld -check build" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
  	</configuration>

   	<configuration name="S60_variant_china_armv5" description="S60 chinese regional variant" filter="S60_5_0,china">
      <unitListRef unitList="PF_BLDVARIANT"/>
      <unitListRef unitList="S60_REGIONALVARIANT"/>

<!-- do what for regional variant that those can be zipped from bldmelast build log file -->
  		<task><buildLayer command="toucher.exe ..\.." unitParallel="Y"/></task>
  		<task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="N"/></task>
      <task><specialInstructions name="clean_version" cwd="\sf\os\deviceplatformrelease\Version\group" command="abld cleanexport -k"/></task> 
<!-- this is not a mistake, bldmake bldfiles and exports have to do twice because of changes in bldvariant.hrh -->
  		<task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="N"/></task>
      <task><buildLayer command="abld makefile" targetList="default_armv5" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld resource" targetList="default_armv5" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld library" targetList="default_armv5" unitParallel="Y" targetParallel="N"/></task>
      <task><buildLayer command="abld target" targetList="default_armv5" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld final" targetList="default_armv5" unitParallel="Y" targetParallel="N"/></task>
      <task><buildLayer command="abld -what build" targetList="default_armv5" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld -check build" targetList="default_armv5" unitParallel="Y" targetParallel="Y"/></task>
  	</configuration>

   	<configuration name="S60_variant_china_winscw" description="S60 chinese regional variant" filter="S60_5_0,china">
      <unitListRef unitList="PF_BLDVARIANT"/>
      <unitListRef unitList="S60_REGIONALVARIANT"/>

<!-- do what for regional variant that those can be zipped from bldmelast build log file -->
  		<task><buildLayer command="toucher.exe ..\.." unitParallel="Y"/></task>
  		<task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="N"/></task>
      <task><specialInstructions name="clean_version" cwd="\sf\os\deviceplatformrelease\Version\group" command="abld cleanexport -k"/></task> 
<!-- this is not a mistake, bldmake bldfiles and exports have to do twice because of changes in bldvariant.hrh -->
  		<task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="N"/></task>
      <task><buildLayer command="abld makefile" targetList="default_winscw" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld resource" targetList="default_winscw" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld library" targetList="default_winscw" unitParallel="Y" targetParallel="N"/></task>
      <task><buildLayer command="abld target" targetList="default_winscw" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld final" targetList="default_winscw" unitParallel="Y" targetParallel="N"/></task>
      <task><buildLayer command="abld -what build" targetList="default_winscw" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld -check build" targetList="default_winscw" unitParallel="Y" targetParallel="Y"/></task>
  	</configuration>

   	<configuration name="S60_variant_japan" description="S60 japanese regional variant" filter="S60_5_0,japan">
      <unitListRef unitList="S60_BLDVARIANT"/>   
      <unitListRef unitList="S60_REGIONALVARIANT"/>

<!-- do what for regional variant that those can be zipped from bldmelast build log file -->
  		<task><buildLayer command="toucher.exe ..\.." unitParallel="Y"/></task>
  		<task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="N"/></task>
      <task><specialInstructions name="clean_version" cwd="\sf\os\deviceplatformrelease\Version\group" command="abld cleanexport -k"/></task> 
<!-- this is not a mistake, bldmake bldfiles and exports have to do twice because of changes in bldvariant.hrh -->
  		<task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="N"/></task>
      <task><buildLayer command="abld makefile" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld resource" targetList="default" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld library" targetList="default" unitParallel="Y" targetParallel="N"/></task>
      <task><buildLayer command="abld target" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld final" targetList="default" unitParallel="Y" targetParallel="N"/></task>
      <task><buildLayer command="abld -what build" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld -check build" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
  	</configuration>

   	<configuration name="S60_variant_japan_winscw" description="S60 japanese regional variant" filter="S60_5_0,japan">
      <unitListRef unitList="PF_BLDVARIANT"/>      
      <unitListRef unitList="S60_REGIONALVARIANT"/>

<!-- do what for regional variant that those can be zipped from bldmelast build log file -->
  		<task><buildLayer command="toucher.exe ..\.." unitParallel="Y"/></task>
  		<task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="N"/></task>
      <task><specialInstructions name="clean_version" cwd="\sf\os\deviceplatformrelease\Version\group" command="abld cleanexport -k"/></task> 
<!-- this is not a mistake, bldmake bldfiles and exports have to do twice because of changes in bldvariant.hrh -->
  		<task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="N"/></task>
      <task><buildLayer command="abld makefile" targetList="default_winscw" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld resource" targetList="default_winscw" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld library" targetList="default_winscw" unitParallel="Y" targetParallel="N"/></task>
      <task><buildLayer command="abld target" targetList="default_winscw" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld final" targetList="default_winscw" unitParallel="Y" targetParallel="N"/></task>
      <task><buildLayer command="abld -what build" targetList="default_winscw" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld -check build" targetList="default_winscw" unitParallel="Y" targetParallel="Y"/></task>
  	</configuration>
  	
   	<configuration name="S60_variant_japan_armv5" description="S60 japanese regional variant" filter="S60_5_0,japan">
      <unitListRef unitList="PF_BLDVARIANT"/>
      <unitListRef unitList="S60_REGIONALVARIANT"/>

<!-- do what for regional variant that those can be zipped from bldmelast build log file -->
  		<task><buildLayer command="toucher.exe ..\.." unitParallel="Y"/></task>
  		<task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="N"/></task>
      <task><specialInstructions name="clean_version" cwd="\sf\os\deviceplatformrelease\Version\group" command="abld cleanexport -k"/></task> 
<!-- this is not a mistake, bldmake bldfiles and exports have to do twice because of changes in bldvariant.hrh -->
  		<task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="N"/></task>
      <task><buildLayer command="abld makefile" targetList="default_armv5" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld resource" targetList="default_armv5" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld library" targetList="default_armv5" unitParallel="Y" targetParallel="N"/></task>
      <task><buildLayer command="abld target" targetList="default_armv5" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld final" targetList="default_armv5" unitParallel="Y" targetParallel="N"/></task>
      <task><buildLayer command="abld -what build" targetList="default_armv5" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld -check build" targetList="default_armv5" unitParallel="Y" targetParallel="Y"/></task>
  	</configuration>  

		<configuration name="S60_5_1_clean" description="S60 5.1 clean build" filter="raptor_S60_5_1_clean">
    	<unitListRef unitList="S60_COMMON_OSEXTENSION"/>
    	<unitListRef unitList="S60_COMMON_OSEXTENSION_OEM"/>
      <unitListRef unitList="S60_COMMON"/>
      <unitListRef unitList="S60_OEM_BUILD"/>
      <unitListRef unitList="S60_COMMON_OSEXTENSION_STUBS"/>
      <unitListRef unitList="S60_COMMON_STUBS"/>
      <unitListRef unitList="S60_BINARY_ONLY"/>
      
      <task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="Y"/></task>
      <task><buildLayer command="abld makefile" targetList="default_tools" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld library" targetList="default_tools" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld target" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld final" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld -what build" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld -check build" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld makefile" targetList="default_winscw" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld resource" targetList="default_winscw" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld library" targetList="default_winscw" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld makefile" targetList="default_armv5" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld resource" targetList="default_armv5" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld library" targetList="default_armv5" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld target" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld final" targetList="default" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld -what build" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld -check build" targetList="default" unitParallel="Y" targetParallel="Y"/></task>
    </configuration>

		<configuration name="S60_5_1_sf" description="S60 5.1 clean build" filter="S60_5_0">
    	<unitListRef unitList="S60_COMMON_OSEXTENSION"/>
      <unitListRef unitList="S60_COMMON"/>
      <unitListRef unitList="S60_SF_BUILD"/>
      <unitListRef unitList="S60_COMMON_OSEXTENSION_STUBS"/>
      <unitListRef unitList="S60_COMMON_STUBS"/>
      <unitListRef unitList="S60_BINARY_ONLY_SF"/>
      
      <task><buildLayer command="bldmake bldfiles" unitParallel="Y"/></task>
      <task><buildLayer command="abld export" unitParallel="Y"/></task>
      <task><buildLayer command="abld makefile" targetList="default_tools" unitParallel="Y" targetParallel="Y"/></task>
      <task><buildLayer command="abld library" targetList="default_tools" unitParallel="N" targetParallel="N"/></task>
      <task><buildLayer command="abld target" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld final" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld -what build" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld -check build" targetList="tools_rel" unitParallel="N" targetParallel="Y"/></task>
      <task><buildLayer command="abld makefile" targetList="default_winscw" unitParallel="Y" targetParallel="Y"/></task>