<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SystemDefinition [
 <!ELEMENT SystemDefinition ( systemModel?, SystemBuild? )>
 <!ATTLIST SystemDefinition
  name CDATA #REQUIRED
  schema CDATA #REQUIRED>
 <!ELEMENT systemModel (layer+)>
 <!ELEMENT layer (block* | collection*)*>
 <!ATTLIST layer
  name CDATA #REQUIRED
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED>
 <!ELEMENT block (subblock* | collection*)*>
 <!ATTLIST block
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED
  level NMTOKEN #IMPLIED
  name CDATA #REQUIRED>
 <!ELEMENT subblock (collection)*>
 <!ATTLIST subblock name CDATA #REQUIRED>
 <!ELEMENT collection (component)*>
 <!ATTLIST collection
  name CDATA #REQUIRED
  level NMTOKEN #IMPLIED>
 <!ELEMENT component (unit)*>
 <!ATTLIST component
  name CDATA #REQUIRED
  deprecated CDATA #IMPLIED
  introduced CDATA #IMPLIED
  contract CDATA #IMPLIED
  plugin (Y|N) "N"
  filter CDATA #IMPLIED
  class NMTOKENS #IMPLIED
  supports CDATA #IMPLIED>
 <!ELEMENT unit EMPTY>
 <!ATTLIST unit
  mrp CDATA #IMPLIED
  filter CDATA #IMPLIED
  bldFile CDATA #IMPLIED
  root CDATA #IMPLIED
  version NMTOKEN #IMPLIED
  prebuilt NMTOKEN #IMPLIED
  late (Y|N) #IMPLIED
  priority CDATA #IMPLIED>
 <!ELEMENT SystemBuild (option* | target+ | targetList+ | list+ | configuration+)*>
 <!ATTLIST SystemBuild schema CDATA #REQUIRED>
 <!ELEMENT list (ref+)>
 <!ATTLIST list
  name ID #REQUIRED
  description CDATA #REQUIRED>
 <!ELEMENT ref EMPTY>
 <!ATTLIST ref item CDATA #REQUIRED>
 <!ELEMENT targetList EMPTY>
 <!ATTLIST targetList
  name ID #REQUIRED
  description CDATA #REQUIRED
  target IDREFS #REQUIRED>
 <!ELEMENT target EMPTY>
 <!ATTLIST target
  name ID #REQUIRED
  abldTarget CDATA #REQUIRED
  description CDATA #REQUIRED>
 <!ELEMENT option EMPTY>
 <!ATTLIST option
  name ID #REQUIRED
  abldOption CDATA #REQUIRED
  description CDATA #REQUIRED
  enable (Y | N ) #REQUIRED>
 <!ELEMENT configuration (listRef+ | ref+ | task+)*>
 <!ATTLIST configuration
  name ID #REQUIRED
  description CDATA #REQUIRED
  filter CDATA #REQUIRED>
 <!ELEMENT task (listRef* , (buildLayer | specialInstructions))>
 <!ELEMENT listRef EMPTY>
 <!ATTLIST listRef list CDATA #REQUIRED>
 <!ELEMENT buildLayer EMPTY>
 <!ATTLIST buildLayer
  command CDATA #REQUIRED
  targetList IDREFS #IMPLIED
  unitParallel (Y | N ) #REQUIRED
  targetParallel (Y | N ) "N">
 <!ELEMENT specialInstructions EMPTY>
 <!ATTLIST specialInstructions
  name CDATA #REQUIRED
  cwd CDATA #REQUIRED
  root CDATA #IMPLIED
  command CDATA #REQUIRED>
]>
<SystemDefinition name="MCL" schema="2.0.0">
  <systemModel>
    <layer name="Tools and Utils and SDKENG" levels="SDK tools test">
      <collection name="Build System Tools" level="tools">
    
        <component name="E32 ToolP">
          <unit bldFile="os\buildtools\sbsv1_os\e32toolp\group" mrp="os\buildtools\sbsv1_os\e32toolp\group\tools_e32toolp.mrp"/>
        </component>
  
        <component name="BUILDSYSTEMTOOLS">
          <unit bldFile="os\buildtools\bldsystemtools\buildsystemtools\group" mrp="os\buildtools\bldsystemtools\buildsystemtools\group\tools_build.mrp"/>
        </component>
        <component name="GT Techview Baseline">
          <unit mrp="os\buildtools\packaging\additionalutils\gt_techview_baseline.mrp"/>
          <!-- DEF087736 This is needed for generating export tables but shouldn't appear otherwise it is included in techview and gt
		     <package name="gt_only_baseline" mrp="os/buildtools/packaging/additionalutils/gt_only_baseline.mrp"/> -->
        </component>
        <component name="Cedar Utils">
          <unit mrp="os\deviceplatformrelease\symbianosbld\cedarutils\tools_utils_cedar.mrp"/>
        </component>
        <component name="Common Utils">
          <unit mrp="os\buildtools\bldsystemtools\commonbldutils\tools_utils_common.mrp"/>
        </component>
        <component name="Additional Utils">
          <unit mrp="os\buildtools\packaging\additionalutils\additional_unknown_cedar.mrp"/>
        </component>
      </collection>
      <collection name="Tools and Utils" level="tools">
        <component name="CTS Functionality Checkers">
          <unit mrp="os\buildtools\toolsandutils\ctsfunctionalitycheckers\Group\testtools_cts_functionalitycheckers.mrp"/>
        </component>
        <component name="BURTESTSERVER">
          <unit bldFile="os\buildtools\toolsandutils\burtestserver\Group" mrp="os\buildtools\toolsandutils\burtestserver\Group\testtools_burtestserver.mrp"/>
        </component>
        <component name="CBRTOOLS" filter="gt">
          <unit bldFile="os\buildtools\toolsandutils\cbrtools\group" mrp="os\buildtools\toolsandutils\cbrtools\group\tools_cbr_tools.mrp"/>
        </component>
        <component name="CBRPRF">
          <unit bldFile="os\buildtools\toolsandutils\prf\group" mrp="os\buildtools\toolsandutils\prf\group\tools_cbr_prf.mrp"/>
        </component>
        <component name="CDB">
          <unit bldFile="os\buildtools\toolsandutils\cdb\group" mrp="os\buildtools\toolsandutils\cdb\group\testtools_cdb.mrp"/>
        </component>
        <component name="CHATSCRIPTS">
          <unit bldFile="mw\remoteconn\connectivitypcside\chatscripts\group" mrp="mw\remoteconn\connectivitypcside\chatscripts\group\testtools_chatscripts.mrp"/>
        </component>
        <component name="DEPCHECK">
          <unit bldFile="os\buildtools\binanamdw_os\depcheck" mrp="os\buildtools\binanamdw_os\depcheck\tools_depcheck.mrp"/>
        </component>
        <component name="E32 Tools" class="PC">
          <unit bldFile="os\buildtools\toolsandutils\e32tools\group" mrp="os\buildtools\toolsandutils\e32tools\group\tools_e32tools.mrp"/>
        </component>
        <component name="E32 Perl Tools" class="PC">
          <unit mrp="os\buildtools\sbsv1_os\e32toolp\group\tools_e32toolp.mrp"/>
        </component>
        <component name="EVALID">
          <unit bldFile="os\buildtools\bintools_os\evalid" mrp="os\buildtools\bintools_os\evalid\tools_evalid.mrp"/>
        </component>
        <component name="KITCOMPARATOR">
          <unit bldFile="os\buildtools\toolsandutils\kitcomparator\group" mrp="os\buildtools\toolsandutils\kitcomparator\group\testtools_cts_kitcomparator.mrp"/>
        </component>
        <component name="LEAVESCAN">
          <unit bldFile="os\buildtools\srcanamdw_os\leavescan\group" mrp="os\buildtools\srcanamdw_os\leavescan\group\testtools_leavescan.mrp"/>
        </component>
        <component name="PROGRAMCHECKER">
          <unit bldFile="os\buildtools\srcanamdw_os\programchecker\group" mrp="os\buildtools\srcanamdw_os\programchecker\group\testtools_programchecker.mrp"/>
        </component>
        <component name="RCOMP">
          <unit bldFile="os\buildtools\bintools_os\rcomp\group" mrp="os\buildtools\bintools_os\rcomp\group\tools_rcomp.mrp"/>
        </component>
        <component name="Redistribution" filter="gt">
          <unit bldFile="os\buildtools\perltoolsplat_os\redistribution" mrp="os\buildtools\perltoolsplat_os\redistribution\tools_redistribution_common.mrp"/>
        </component>
        <component name="WinC Redistribution">
          <unit mrp="os\buildtools\dist_os\redistributionwinceka2\tools_redistribution_winc.mrp"/>
        </component>
        <component name="Additional Redistribution">
          <unit mrp="os\buildtools\perltoolsplat_os\redistribution\additional_tools.mrp"/>
        </component>
        <component name="RESOURCE_HANDLER" contract="Symbian_Affiliate">
          <unit mrp="app\techview\testapps\rschandler\TVResourceHandler\group\Testtools_ResourceHandler_gt.mrp"/>
        </component>
        <component name="ROMKIT_EKA2">
          <unit bldFile="os\buildtools\imgtools_os\romkiteka2\group" mrp="os\buildtools\imgtools_os\romkiteka2\group\tools_romkit.mrp"/>
        </component>
        <component name="MIGRATIONTOOL">
          <unit bldFile="os\buildtools\srcanamdw_os\migrationtool\group" mrp="os\buildtools\srcanamdw_os\migrationtool\group\testtools_migrationtool.mrp"/>
        </component>
        <component name="TESTDRIVER">
          <unit bldFile="os\buildtools\toolsandutils\testdriver\Group" mrp="os\buildtools\toolsandutils\testdriver\Group\testtools_testdriver.mrp"/>
        </component>
        <component name="S60 Compatibility Headers" filter="gt">
          <unit version="9.4" bldFile="os\ossrv\genericservices\s60compatibilityheaders\group94" mrp="os\ossrv\genericservices\s60compatibilityheaders\group94\tools_s60_header_compat94.mrp"/>
          <unit version="9.5" bldFile="os\ossrv\genericservices\s60compatibilityheaders\group95" mrp="os\ossrv\genericservices\s60compatibilityheaders\group95\tools_s60_header_compat95.mrp" filter="!tb91sf"/>
          <unit version="9.6" bldFile="os\ossrv\genericservices\s60compatibilityheaders\group96" mrp="os\ossrv\genericservices\s60compatibilityheaders\group96\tools_s60_header_compat96.mrp" filter="!tb91sf"/>
          <unit version="Future" bldFile="os\ossrv\genericservices\s60compatibilityheaders\groupfuture" mrp="os\ossrv\genericservices\s60compatibilityheaders\groupfuture\tools_s60_header_compatfuture.mrp" filter="!tb91sf"/>
        </component>
        <component name="SMOKETEST" filter="gt">
          <unit bldFile="app\techview\buildverification\smoketest\Group" mrp="app\techview\buildverification\smoketest\Group\testtools_smoketest.mrp"/>
        </component>
        <component name="Stat API" filter="gt">
          <unit bldFile="os\buildtools\toolsandutils\statapi\source\statapi\console" mrp="os\buildtools\toolsandutils\statapi\group\testtools_stat_device_gt.mrp"/>
        </component>
        <component name="Stat Source" contract="Symbian_Affiliate" filter="gt">
          <unit mrp="os\buildtools\toolsandutils\statsource\group\testtools_stat_common_source.mrp"/>
        </component>
        <component name="STAT_DESKTOP" contract="Symbian_Affiliate" filter="gt">
          <unit bldFile="os\buildtools\toolsandutils\statdesktop\group" mrp="os\buildtools\toolsandutils\statdesktop\group\testtools_stat_desktop.mrp"/>
        </component>
        <component name="Bluetooth Logging Engine" introduced="9.2" class="test">
          <unit bldFile="os\shortlinksrv\bluetooth\btlogger\group" mrp="os\shortlinksrv\bluetooth\btlogger\group\bluetooth_logger.mrp"/>
        </component>
        <component name="TESTEXECUTE">
          <unit bldFile="os\osrndtools\testexecfw1\testexecute\Group" mrp="os\osrndtools\testexecfw1\testexecute\Group\tools_testexecute.mrp"/>
        </component>
        <component name="Test Tools Desktop" filter="gt">
          <unit bldFile="os\buildtools\toolsandutils\testtoolsdesktop\group" mrp="os\buildtools\toolsandutils\testtoolsdesktop\group\testtools_desktop.mrp"/>
        </component>
        <component name="Wintunnel">
          <unit mrp="os\buildtools\toolsandutils\wintunnel\group\testtools_WinTunnel_srconly.mrp"/>
        </component>
        <component name="Use Case Controller">
          <unit bldFile="os\buildtools\toolsandutils\usecasecontroller\BuildScripts\group" mrp="os\buildtools\toolsandutils\usecasecontroller\BuildScripts\group\testtools_ucc.mrp"/>
        </component>
        <component name="CINIDATA">
          <unit bldFile="os\osrndtools\testexecfw1\cinidata" mrp="os\osrndtools\testexecfw1\cinidata\tools_cinidata.mrp"/>
        </component>
        <component name="AUTOTEST">
          <unit bldFile="os\buildtools\toolsandutils\autotest\group" mrp="os\buildtools\toolsandutils\autotest\group\tools_autotest.mrp"/>
        </component>
        <component name="TESTCONFIGFILEPARSER">
          <unit bldFile="os\buildtools\toolsandutils\testconfigfileparser\group" mrp="os\buildtools\toolsandutils\testconfigfileparser\group\tools_testconfigfileparser.mrp"/>
        </component>
        <component name="KITSETUPAPP" filter="gt">
          <unit mrp="os\buildtools\toolsandutils\kitsetupapp\group\tools_devkits_kitsetupapp.mrp"/>
        </component>
        <component name="NAVIGATION_PAGES">
          <unit mrp="os\buildtools\toolsandutils\navigationpages\tools_sdk_eng_NavigationPages.mrp"/>
        </component>
        <component name="PRODUCTINSTALLER" filter="gt">
          <unit bldFile="os\buildtools\toolsandutils\productinstaller\group" mrp="os\buildtools\toolsandutils\productinstaller\group\tools_custkits_productinstaller.mrp"/>
        </component>
        <component name="REDISTRIBUTION_WINC_EKA2">
          <unit bldFile="os\buildtools\dist_os\redistributionwinceka2" mrp="os\buildtools\dist_os\redistributionwinceka2\tools_redistribution_cedar.mrp"/>
        </component>
        <component name="MakeKeys" filter="gt" introduced="6.0" class="PC">
          <unit bldFile="mw\appinstall\secureswitools\makekeys\group" mrp="mw\appinstall\secureswitools\makekeys\group\security_makekeys.mrp"/>
        </component>
        <component name="CAPTOOLS">
          <unit bldFile="os\buildtools\binanamdw_os\captools\group" mrp="os\buildtools\binanamdw_os\captools\group\testtools_captools.mrp"/>
        </component>
        <component name="Packet Loopback CSY" introduced="8.1" class="test">
          <unit bldFile="os\commsfw\serialserver\packetloopbackcsy\group" mrp="os\commsfw\serialserver\packetloopbackcsy\group\PacketLoopbackCSY.mrp"/>
        </component>
        <component name="UTRACE" introduced="9.3" deprecated="9.4">
          <unit bldFile="os\persistentdata\traceservices\utrace\group" mrp="os\persistentdata\traceservices\utrace\group\testtools_utrace_api.mrp"/>
        </component>
        <component name="STLPORT">
          <unit bldFile="os\buildtools\toolsandutils\stlport\group" mrp="os\buildtools\toolsandutils\stlport\group\tools_stlport.mrp"/>
        </component>
      </collection>
      <collection name="Developer Library" level="test">
        <component name="Developer Library Tools" class="placeholder">
          <!-- placeholder for  mrp="os/buildtools/devlib/devlibhelp/tools/developerlibrary_tools.mrp" -->
        </component>
        <component name="Developer Library Help">
          <unit version="9.4" bldFile="os\buildtools\devlib\devlibhelp\group\devlib94" mrp="os\buildtools\devlib\devlibhelp\group\devlib94\developerlibrary_doc_html.mrp"/>
          <unit version="9.5" bldFile="os\buildtools\devlib\devlibhelp\group\devlib95" mrp="os\buildtools\devlib\devlibhelp\group\devlib95\developerlibrary_doc_html.mrp" filter="!tb91sf"/>
        </component>
        <component name="Developer Library Source" filter="gt">
          <unit bldFile="os\buildtools\devlib\devlibhelp\securitysupplement\doc_source" mrp="os\buildtools\devlib\devlibhelp\developerlibrary_doc_source.mrp"/>
        </component>
        <component name="Developer Library HTML">
          <unit mrp="os\buildtools\devlib\devlibhelp\group\shared\developerlibrary_doc_plain_html.mrp"/>
        </component>
        <!-- lots of subsystem documentation packages -->
        <component name="Application Engines Documentation" class="doc">
          <unit mrp="app\organizer\pimappservices\appenginesdocs\app-engines_documentation.mrp"/>
        </component>
        <component name="UI Frameworks Documentation" class="doc">
          <unit mrp="mw\classicui\commonuisupport\uifwsdocs\app-framework_documentation.mrp"/>
        </component>
        <component name="Application Services Documentation" class="doc">
          <unit mrp="mw\appsupport\commonappservices\appservicesdocs\app-services_documentation.mrp"/>
        </component>
        <component name="Base Documentation">
          <unit mrp="os\kernelhwsrv\userlibandfileserver\basedocs\base_documentation.mrp"/>
        </component>
        <component name="Bluetooth Documentation" class="doc">
          <unit mrp="os\shortlinksrv\bluetooth\btdocs\bluetooth_documentation.mrp"/>
        </component>
        <component name="Comms Infrastructure Documentation" introduced="7.0" class="doc">
          <unit mrp="os\commsfw\commsfw_info\commsinfrastructuredocs\comms-infras_documentation.mrp"/>
        </component>
        <component name="Graphics Documentation" contract="Symbian_Affiliate" class="doc">
          <unit mrp="os\graphics\graphics_info\graphicsdocs\graphics_documentation.mrp"/>
        </component>
        <component name="Multimedia Documentation">
          <unit mrp="os\mm\mm_info\mmdocs\multimedia_documentation.mrp"/>
        </component>
        <component name="Networking Documentation" class="doc">
          <unit mrp="os\networkingsrv\networkingsrv_info\networkingdocs\networking_documentation.mrp"/>
        </component>
        <component name="Security Documentation">
          <unit mrp="os\security\cryptomgmtlibs\securitydocs\security_documentation.mrp"/>
        </component>
        <component name="Shortlink Documentation">
          <unit mrp="os\commsfw\serialserver\c32serialserverdocs\ser-comms_documentation.mrp"/>
        </component>
        <component name="Syslibs Documentation" class="doc">
          <unit mrp="os\ossrv\genericservices\syslibsdocs\syslibs_documentation.mrp"/>
        </component>
        <component name="System Documentation" class="doc">
          <unit mrp="os\deviceplatformrelease\foundation_system\systemdocs\group\system.mrp"/>
        </component>
        <component name="Telephony Confidential Documentation" class="doc">
          <unit mrp="os\cellularsrv\cellularsrv_info\telephonyconfidentialdocs\telephony_confidential.mrp"/>
        </component>
        <component name="Telephony Documentation" class="doc">
          <unit mrp="os\cellularsrv\cellularsrv_info\telephonydocs\telephony_documentation.mrp"/>
        </component>
        <component name="Tools Documentation">
          <unit mrp="os\buildtools\devlib\toolsdocs\tools_documentation.mrp"/>
        </component>
        <component name="USB Class and Manager Documentation" class="doc">
          <unit mrp="os\shortlinksrv\usbmgmt\usbclassandmgrdocs\usb_documentation.mrp"/>
        </component>
      </collection>
      <collection name="SDKENG" level="SDK">
        <component name="RUNPERL" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\runperl\group" mrp="os\buildtools\misccomponents\runperl\group\tools_sdk_eng_runperl.mrp"/>
        </component>
        <component name="BUILD-TOOLS" filter="gt">
          <unit bldFile="os\buildtools\sbsv1_os\bldtools\group" mrp="os\buildtools\sbsv1_os\bldtools\group\tools_sdk_eng_build-tools.mrp"/>
        </component>
        <component name="JAVALIBRARY" filter="gt">
          <unit bldFile="os\buildtools\javatoolsplat\javalib\group" mrp="os\buildtools\javatoolsplat\javalib\group\tools_sdk_eng_javalibrary.mrp"/>
        </component>
        <component name="ASSERTION" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\assertion\group" mrp="os\buildtools\misccomponents\assertion\group\tools_sdk_eng_assertion.mrp"/>
        </component>
        <component name="ENUM" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\enum\group" mrp="os\buildtools\misccomponents\enum\group\tools_sdk_eng_enum.mrp"/>
        </component>
        <component name="LOGGER" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\logger\group" mrp="os\buildtools\misccomponents\logger\group\tools_sdk_eng_logger.mrp"/>
        </component>
        <component name="FILESYS" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\filesys\group" mrp="os\buildtools\misccomponents\filesys\group\tools_sdk_eng_filesys.mrp"/>
        </component>
        <component name="ENVVAR" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\envvar\group" mrp="os\buildtools\misccomponents\envvar\group\tools_sdk_eng_envvar.mrp"/>
        </component>
        <component name="INSTALLUTILS" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\installutils\group" mrp="os\buildtools\misccomponents\installutils\group\tools_sdk_eng_installutils.mrp"/>
        </component>
        <component name="MNEMONICFIX" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\mnemonicfix\group" mrp="os\buildtools\misccomponents\mnemonicfix\group\tools_sdk_eng_mnemonicfix.mrp"/>
        </component>
        <component name="PATHBROWSER" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\pathbrowser\group" mrp="os\buildtools\misccomponents\pathbrowser\group\tools_sdk_eng_pathbrowser.mrp"/>
        </component>
        <component name="SHELLEXEC" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\shellexec\group" mrp="os\buildtools\misccomponents\shellexec\group\tools_sdk_eng_shellexec.mrp"/>
        </component>
        <component name="SWINGWORKER" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\swingworker\group" mrp="os\buildtools\misccomponents\swingworker\group\tools_sdk_eng_swingworker.mrp"/>
        </component>
        <component name="TESTCASERUNNER" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\testcaserunner\group" mrp="os\buildtools\misccomponents\testcaserunner\group\tools_sdk_eng_testcaserunner.mrp"/>
        </component>
        <component name="TOOLBARPANEL" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\toolbarpanel\group" mrp="os\buildtools\misccomponents\toolbarpanel\group\tools_sdk_eng_toolbarpanel.mrp"/>
        </component>
        <component name="JAVAHELP" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\javahelp\group" mrp="os\buildtools\misccomponents\javahelp\group\tools_sdk_eng_javahelp.mrp"/>
        </component>
        <component name="LANGCONFIG" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\langconfig\group" mrp="os\buildtools\misccomponents\langconfig\group\tools_sdk_eng_langconfig.mrp"/>
        </component>
        <component name="MBMCODEC" filter="gt">
          <unit bldFile="app\helps\symhelp\mbmcodec\group" mrp="app\helps\symhelp\mbmcodec\group\tools_sdk_eng_mbmcodec.mrp"/>
        </component>
        <component name="SDKINFO" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\sdkinfo\group" mrp="os\buildtools\misccomponents\sdkinfo\group\tools_sdk_eng_sdkinfo.mrp"/>
        </component>
        <component name="JADE" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\jade\group" mrp="os\buildtools\misccomponents\jade\group\tools_sdk_eng_jade.mrp"/>
        </component>
        <component name="CSHLPCMP_GUI" filter="gt">
          <unit bldFile="app\helps\symhelp\cshlpcmpgui\group" mrp="app\helps\symhelp\cshlpcmpgui\group\tools_sdk_eng_cshlpcmp_gui.mrp" priority="1010"/>
        </component>
        <component name="SDK Package Manager" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\sdkpackagemgr\group" mrp="os\buildtools\misccomponents\sdkpackagemgr\group\tools_sdk_eng_sdkpkg-manager.mrp"/>
        </component>
        <component name="Production Build Tools" filter="gt">
          <unit mrp="os\buildtools\toolsandutils\productionbldtools\product_tools.mrp"/>
        </component>
        <component name="Production Build CBR Configuration Files" filter="gt">
          <unit mrp="os\deviceplatformrelease\symbianosbld\productionbldcbrconfig\product_cbr_config.mrp"/>
        </component>
        <component name="SDKPKG-TOOLS" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\sdkpkgtools\group" mrp="os\buildtools\misccomponents\sdkpkgtools\group\tools_sdk_eng_sdkpkg-tools.mrp"/>
        </component>
        <component name="EMULATOR_LAUNCHER" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\emulatorlauncher\group" mrp="os\buildtools\misccomponents\emulatorlauncher\group\tools_sdk_eng_emulator_launcher.mrp"/>
        </component>
        <component name="PKGMGRGUI" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\pkgmgrgui\group" mrp="os\buildtools\misccomponents\pkgmgrgui\group\tools_sdk_eng_pkgmgrgui.mrp"/>
        </component>
        <component name="LAUNCH" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\launch\group" mrp="os\buildtools\misccomponents\launch\group\tools_sdk_eng_launch.mrp"/>
        </component>
        <component name="TOOLS_STUBS" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\toolsstubs\group" mrp="os\buildtools\misccomponents\toolsstubs\group\tools_sdk_eng_tools_stubs.mrp"/>
        </component>
        <component name="BSPBUILDER" filter="gt">
          <unit bldFile="os\buildtools\misccomponents\bspbuilder\group" mrp="os\buildtools\misccomponents\bspbuilder\group\tools_bspbuilder.mrp"/>
        </component>
        <component name="ALP2CSH">
          <unit bldFile="os\buildtools\fileconv\alp2csh\group" mrp="os\buildtools\fileconv\alp2csh\group\tools_sdk_eng_alp2csh.mrp"/>
        </component>
        <component name="CJPEG">
          <unit bldFile="os\buildtools\fileconv\cjpeg\group" mrp="os\buildtools\fileconv\cjpeg\group\tools_sdk_eng_cjpeg.mrp"/>
        </component>
        <component name="CSHLPCMP Frontend">
          <unit bldFile="app\helps\symhelp\cshlpcmpfrontend\group" mrp="app\helps\symhelp\cshlpcmpfrontend\group\tools_sdk_eng_cshlpcmp_frontend.mrp"/>
        </component>
        <component name="CSHLPCMP Backend">
          <unit mrp="app\helps\symhelp\cshlpcmpbackend\group\tools_sdk_eng_cshlpcmp_backend_srconly.mrp"/>
        </component>
        <component name="PERLLIBRARY">
          <unit bldFile="os\buildtools\perltoolsplat_os\legacycommonperl\group" mrp="os\buildtools\perltoolsplat_os\legacycommonperl\group\tools_sdk_eng_perllibrary.mrp"/>
        </component>
        <component name="Perl Shared Libraries">
          <unit bldFile="os\buildtools\perltoolsplat_os\commonperl\group" mrp="os\buildtools\perltoolsplat_os\commonperl\group\tools_sdk_eng_perl_shared.mrp"/>
        </component>
        <component name="RTF2PTML">
          <unit bldFile="os\buildtools\fileconv\rtf2ptml\group" mrp="os\buildtools\fileconv\rtf2ptml\group\tools_sdk_eng_rtf2ptml.mrp"/>
        </component>
        <component name="SPLASH">
          <unit bldFile="os\buildtools\misccomponents\splash\group" mrp="os\buildtools\misccomponents\splash\group\tools_sdk_eng_splash.mrp"/>
        </component>
        <component name="SDK Builder">
          <unit bldFile="os\buildtools\misccomponents\sdkbuilder\group" mrp="os\buildtools\misccomponents\sdkbuilder\group\tools_sdk_eng_sdk_builder.mrp"/>
        </component>
      </collection>
      <collection name="Test Product" level="test">
		<!-- PLACEHOLDER="DS.1603" START REMOVE-->
        <component name="Bluetooth Test Product" introduced="9.2" class="test">
        </component>
        <component name="Multimedia Test Product">
        </component>
		<!-- PLACEHOLDER="DS.1603" END REMOVE-->
        <component name="Messaging Test Product">
          <unit mrp="mw\messagingmw\messagingfw\msgtestproduct\group\messaging_testproduct.mrp"/>
        </component>
		<!-- PLACEHOLDER="DS.1603" START REMOVE-->
        <component name="Syslibs Test Product">
        </component>
        <component name="Comms Infrastructure Test Product" introduced="9.2" class="test">
        </component>
        <component name="Graphics Test Product">
        </component>
		<!-- PLACEHOLDER="DS.1603" END REMOVE-->
        <component name="LBS Test Product" introduced="9.2" class="test">
          <unit mrp="os\lbs\lbstest\lbstestproduct\group\lbs_testproduct.mrp"/>
        </component>
      </collection>
    </layer>
    <layer name="HAL" levels="Hardware-dependent">
      <block name="Board Support Packages" level="Hardware-dependent">
			<collection name="HAI Test Suites">
		<component name="BSP Verification Suite" class="placeholder" introduced="TB91">
			<!-- PLACEHOLDER="DS.1603"
			<unit mrp="os/boardsupport/haitest/group/bspsvs.mrp"/>
			-->
		</component>
		</collection>
        <collection name="Emulator">
          <component name="Emulator BSP" contract="Symbian_SD4C">
            <unit bldFile="os\boardsupport\emulator\emulatorbsp" mrp="os\boardsupport\emulator\emulatorbsp\base_wins.mrp"/>
          </component>
          <component name="Unistore2 Emulator Support" contract="NAND_Flash_XSR_Unistore_2_Other_Portions" filter="gt" introduced="9.4">
            <unit bldFile="os\boardsupport\emulator\unistore2emulatorsupport" mrp="os\boardsupport\emulator\unistore2emulatorsupport\base_wins_unistore2.mrp"/>
          </component>
        </collection>
        <collection name="OMAP H2">
          <component name="OMAP H2 BSP" introduced="9.0">
            <unit bldFile="os\boardsupport\omaph2\omaph2bsp\h2" mrp="os\boardsupport\omaph2\omaph2bsp\h2\base_omaph2.mrp"/>
          </component>
          <component name="OMAP H2 Unistore2" contract="NAND_Flash_XSR_Unistore_2_Other_Portions" filter="gt" introduced="9.1">
            <unit bldFile="os\boardsupport\omaph2\omaph2unistore2" mrp="os\boardsupport\omaph2\omaph2unistore2\base_h2_unistore2.mrp"/>
          </component>
          <component name="OMAP H2 SDIO" filter="gt" introduced="9.2">
            <unit bldFile="os\boardsupport\omaph2\omaph2sdio" mrp="os\boardsupport\omaph2\omaph2sdio\base_h2_sdio.mrp"/>
          </component>
        </collection>
        <collection name="OMAP H4">
          <component name="OMAP H4 BSP">
            <unit bldFile="os\boardsupport\omaph4\omaph4bsp\h4" mrp="os\boardsupport\omaph4\omaph4bsp\h4\base_omaph4hrp.mrp"/>
          </component>
          <component name="H4 Boot Loader" introduced="9.1">