<?xml version="1.0"?>
<!DOCTYPE SystemDefinition [
<!ELEMENT SystemDefinition ( systemModel )>
<!ATTLIST SystemDefinition
  name CDATA #REQUIRED
  schema CDATA #REQUIRED
>
<!-- all paths are relative to the environment variable specified by the root attribute, or SOURCEROOT if not.  -->
<!-- System Model Section of DTD -->
<!ELEMENT systemModel (layer+)>
<!ELEMENT layer (block* | collection*)*>
<!-- Kernel Services, Base Services, OS Services, Etc -->
<!ATTLIST layer
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED
>
<!ELEMENT block (subblock* | collection*)*>
 <!-- Generic OS services, Comms Services, etc -->
<!ATTLIST block
  levels NMTOKENS #IMPLIED
  span CDATA #IMPLIED
  level NMTOKEN #IMPLIED
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
>
<!ELEMENT subblock (collection)*>
<!-- Cellular Baseband Services, Networking Services, etc -->
<!ATTLIST subblock
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
>
<!ELEMENT collection (component)*>
<!-- Screen Driver, Content Handling, etc -->
<!ATTLIST collection
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  level NMTOKEN #IMPLIED
>
<!ELEMENT component (unit)*>
<!-- contains units or is a  package or prebuilt -->
<!ATTLIST component
  name CDATA #REQUIRED
  long-name CDATA #IMPLIED
  deprecated CDATA #IMPLIED
  introduced CDATA #IMPLIED
  contract CDATA #IMPLIED
  plugin (Y|N) "N"
  filter CDATA #IMPLIED
  class NMTOKENS #IMPLIED
  supports CDATA #IMPLIED
  purpose ( optional | mandatory | development ) "optional"
>
<!ELEMENT unit EMPTY >
<!-- must be buildable (bld.inf) -->
<!ATTLIST unit
  mrp CDATA #IMPLIED
  filter CDATA #IMPLIED
  root CDATA #IMPLIED
  version NMTOKEN #IMPLIED
  prebuilt NMTOKEN #IMPLIED
  late (Y|N) #IMPLIED
  priority CDATA #IMPLIED
>
]>
<SystemDefinition name="Symbian" schema="2.0.1">
  <systemModel>
    <layer name="os" long-name="OS" levels="hw services">
      <block name="kernelhwsrv" level="hw" long-name="Kernel and Hardware Services" levels="hw-if adaptation framework test">
        <collection name="baseintegtests" long-name="Base Integration Testing" level="test">
          <component name="baseintegrationtest" long-name="Base Integration Test" introduced="9.3" purpose="development">
            <unit bldFile="os/kernelhwsrv/baseintegtests/baseintegrationtest/group" mrp="os/kernelhwsrv/baseintegtests/baseintegrationtest/group/base_integration_test.mrp"/>
          </component>
        </collection>
        <collection name="brdbootldr" long-name="Board Boot Loader" level="hw-if">
          <component name="ubootldr" long-name="Boot Loader" introduced="9.2" purpose="optional">
            <unit mrp="os/kernelhwsrv/brdbootldr/ubootldr/base_ubootldr.mrp"/>
          </component>
        </collection>
        <collection name="unistore2" long-name="UniStore2 Flash Translation Layer" level="hw-if">
          <component name="uiicore" long-name="UniStore2 Core" filter="gt" introduced="9.1" purpose="optional">
            <unit mrp="os/kernelhwsrv/kernel/eka/drivers/unistore2/base_drivers_unistore2_undeliverable.mrp"/>
          </component>
        </collection>
        <collection name="bsptemplate" long-name="BSP Template" level="hw-if">
          <component name="asspandvariant" long-name="Template ASSP and Variant" introduced="6.0" purpose="development">
            <unit bldFile="os/kernelhwsrv/bsptemplate/asspandvariant/template_variant" mrp="os/kernelhwsrv/bsptemplate/asspandvariant/base_template.mrp"/>
          </component>
        </collection>
        <collection name="kernel" long-name="Kernel Architecture" level="adaptation">
          <component name="eka" long-name="Kernel Architecture" introduced="8.0" purpose="mandatory">
            <unit bldFile="os/kernelhwsrv/kernel/eka" mrp="os/kernelhwsrv/kernel/eka/base_e32.mrp"/>
          </component>
        </collection>
        <collection name="ldds" long-name="Logical Device Drivers" level="adaptation">
          <component name="ethernetldd" long-name="Ethernet Drivers" purpose="optional">
            <unit bldFile="os/kernelhwsrv/kernel/eka/drivers/ethernet" mrp="os/kernelhwsrv/kernel/eka/drivers/ethernet/base_e32_drivers_ethernet.mrp"/>
          </component>
          <component name="audioldd" long-name="Audio Drivers" introduced="8.1b" purpose="optional">
            <unit bldFile="os/kernelhwsrv/kernel/eka/drivers/esound" mrp="os/kernelhwsrv/kernel/eka/drivers/esound/base_e32_drivers_sound.mrp"/>
          </component>
          <component name="serialldd" long-name="Serial Port Drivers" purpose="optional">
            <unit bldFile="os/kernelhwsrv/kernel/eka/drivers/ecomm" mrp="os/kernelhwsrv/kernel/eka/drivers/ecomm/base_e32_drivers_ecomm.mrp"/>
          </component>
          <component name="legacydrivers" long-name="Legacy Drivers" purpose="optional">
            <unit mrp="os/kernelhwsrv/kernel/eka/drivers/adc/base_e32_drivers_adc.mrp"/>
          </component>
          <component name="locmedia" long-name="Local Media Subsystem" introduced="8.1b" purpose="mandatory">
<!-- these are LDDs for storage media-->
            <unit bldFile="os/kernelhwsrv/kernel/eka/drivers/locmedia" mrp="os/kernelhwsrv/kernel/eka/drivers/locmedia/base_e32_drivers_locmedia.mrp"/>
          </component>
          <component name="runmodedebugger" long-name="Run Mode Debugger" purpose="mandatory">
            <unit bldFile="os/kernelhwsrv/kernel/eka/drivers/debug" mrp="os/kernelhwsrv/kernel/eka/drivers/debug/base_e32_drivers_debug.mrp"/>
          </component>
          <component name="btrace" long-name="Kernel Trace Tool" purpose="mandatory">
            <unit bldFile="os/kernelhwsrv/kernel/eka/drivers/trace" mrp="os/kernelhwsrv/kernel/eka/drivers/trace/base_e32_drivers_trace.mrp"/>
          </component>
        </collection>
        <collection name="driversupport" long-name="Generic Driver Support" level="hw-if">
          <component name="mediadrivers" long-name="Media Drivers" purpose="optional">
<!-- these are for storage media-->
          </component>
          <component name="genericboardsupport" long-name="Generic Board Support" purpose="optional">
            <unit bldFile="os/kernelhwsrv/kernel/eka/drivers/bsp" mrp="os/kernelhwsrv/kernel/eka/drivers/bsp/base_e32_drivers_bsp.mrp"/>
          </component>
        </collection>
        <collection name="userlibandfileserver" long-name="User Library and File Server" level="framework">
          <component name="euser" long-name="User Library" purpose="mandatory">
            <unit bldFile="os/kernelhwsrv/kernel/eka/euser" mrp="os/kernelhwsrv/kernel/eka/euser/base_e32_euser.mrp"/>
          </component>
          <component name="fileserver" long-name="File Server" filter="gt" purpose="mandatory">
            <unit bldFile="os/kernelhwsrv/userlibandfileserver/fileserver/group" mrp="os/kernelhwsrv/userlibandfileserver/fileserver/group/base_f32.mrp"/>
          </component>
          <component name="estart" long-name="Base Starter" filter="gt" purpose="optional">
            <unit bldFile="os/kernelhwsrv/userlibandfileserver/fileserver/estart" mrp="os/kernelhwsrv/userlibandfileserver/fileserver/estart/base_f32_estart.mrp"/>
          </component>
          <component name="domainmgr" long-name="Domain Manager" introduced="8.1b" purpose="mandatory">
            <unit bldFile="os/kernelhwsrv/userlibandfileserver/domainmgr/group" mrp="os/kernelhwsrv/userlibandfileserver/domainmgr/group/base_domain.mrp"/>
          </component>
          <component name="basedocs" long-name="Base Documentation" purpose="development">
            <unit mrp="os/kernelhwsrv/userlibandfileserver/basedocs/base_documentation.mrp"/>
          </component>
        </collection>
        <collection name="filesystems" long-name="File Systems" level="framework">
          <component name="romfs" long-name="ROM File System" filter="gt" purpose="optional" plugin="Y">
            <unit mrp="os/kernelhwsrv/userlibandfileserver/fileserver/srom/base_f32_srom.mrp"/>
          </component>
          <component name="rofs" long-name="ROFS" filter="gt" purpose="optional" plugin="Y">
            <unit bldFile="os/kernelhwsrv/userlibandfileserver/fileserver/srofs" mrp="os/kernelhwsrv/userlibandfileserver/fileserver/srofs/base_f32_srofs.mrp"/>
          </component>
          <component name="usbmsfs" long-name="USB Mass Storage File System" filter="gt" purpose="optional" plugin="Y">
            <unit bldFile="os/kernelhwsrv/userlibandfileserver/fileserver/smassstorage" mrp="os/kernelhwsrv/userlibandfileserver/fileserver/smassstorage/base_f32_smassstorage.mrp"/>
          </component>
          <component name="fat32fs" long-name="FAT32 File System" filter="gt" purpose="optional" plugin="Y">
            <unit bldFile="os/kernelhwsrv/userlibandfileserver/fileserver/sfat32" mrp="os/kernelhwsrv/userlibandfileserver/fileserver/sfat32/base_f32_sfat32.mrp"/>
          </component>
          <component name="fatfs" long-name="FAT File System" filter="gt" purpose="optional" plugin="Y">
            <unit bldFile="os/kernelhwsrv/userlibandfileserver/fileserver/sfat" mrp="os/kernelhwsrv/userlibandfileserver/fileserver/sfat/base_f32_sfat.mrp"/>
          </component>
          <component name="compfs" long-name="Composite File System" filter="gt" purpose="optional" plugin="Y">
            <unit bldFile="os/kernelhwsrv/userlibandfileserver/fileserver/scomp" mrp="os/kernelhwsrv/userlibandfileserver/fileserver/scomp/base_f32_scomp.mrp"/>
          </component>
        </collection>
        <collection name="halservices" long-name="HAL Services" level="framework">
          <component name="hal" long-name="User-Side Hardware Abstraction" introduced="6.0" purpose="optional">
            <unit bldFile="os/kernelhwsrv/halservices/hal" mrp="os/kernelhwsrv/halservices/hal/base_hal.mrp"/>
          </component>
        </collection>
        <collection name="textmodeshell" long-name="Text Mode Shell" level="test">
          <component name="e32wsrv" long-name="Text Window Server" purpose="optional">
            <unit bldFile="os/kernelhwsrv/kernel/eka/ewsrv" mrp="os/kernelhwsrv/kernel/eka/ewsrv/base_e32_ewsrv.mrp"/>
          </component>
          <component name="textshell" long-name="Text Shell" filter="gt" purpose="development">
            <unit bldFile="os/kernelhwsrv/userlibandfileserver/fileserver/etshell" mrp="os/kernelhwsrv/userlibandfileserver/fileserver/etshell/base_f32_eshell.mrp"/>
          </component>
        </collection>
      </block>
      <block name="boardsupport" level="hw" long-name="Board Support" levels="bsp test 2 3 4">
        <collection name="emulator" long-name="Emulator" level="bsp">
          <component name="emulatorbsp" long-name="Emulator BSP" purpose="optional">
            <unit bldFile="os/boardsupport/emulator/emulatorbsp" mrp="os/boardsupport/emulator/emulatorbsp/base_wins.mrp"/>
          </component>
        </collection>
      </block>
      <block name="buildtools" level="hw" long-name="Build Tools" levels="bld mw fw ui">
        <collection name="bldsystemtools" long-name="Build System Tools" level="bld">
          <component name="buildsystemtools" long-name="Build System Tools" purpose="development">
            <unit bldFile="os/buildtools/bldsystemtools/buildsystemtools/group" mrp="os/buildtools/bldsystemtools/buildsystemtools/group/tools_build.mrp"/>
          </component>
          <component name="gttechviewbaseline" long-name="GT Techview Baseline" purpose="development">
            <unit mrp="os/buildtools/packaging/additionalutils/gt_techview_baseline.mrp"/>
          </component>
          <component name="commonbldutils" long-name="Common Utils" purpose="development">
            <unit mrp="os/buildtools/bldsystemtools/commonbldutils/tools_utils_common.mrp"/>
          </component>
        </collection>
        <collection name="packaging" long-name="Packaging" level="ui">
          <component name="additionalutils" long-name="Additional Utils" purpose="development">
            <unit mrp="os/buildtools/packaging/additionalutils/additional_unknown_cedar.mrp"/>
          </component>
        </collection>
        <collection name="toolsandutils" long-name="Tools and Utils" level="mw">
          <component name="productionbldtools" long-name="Production Build Tools" filter="gt" purpose="development">
            <unit mrp="os/buildtools/toolsandutils/productionbldtools/product_tools.mrp"/>
          </component>
          <component name="ctsfunctionalitycheckers" long-name="CTS Functionality Checkers" purpose="development">
            <unit mrp="os/buildtools/toolsandutils/ctsfunctionalitycheckers/Group/testtools_cts_functionalitycheckers.mrp"/>
          </component>
          <component name="e32tools" long-name="E32 Tools" deprecated="tb91" purpose="development" class="PC">
            <unit bldFile="os/buildtools/toolsandutils/e32tools/group" mrp="os/buildtools/toolsandutils/e32tools/group/tools_e32tools.mrp"/>
          </component>
          <component name="wincredistribution" long-name="WinC Redistribution" purpose="development">
            <unit mrp="os/buildtools/dist_os/redistributionwinceka2/tools_redistribution_winc.mrp"/>
          </component>
          <component name="additionalredistribution" long-name="Additional Redistribution" purpose="development">
            <unit mrp="os/buildtools/perltoolsplat_os/redistribution/additional_tools.mrp"/>
          </component>
          <component name="statsource" long-name="STAT Source" filter="gt" purpose="development">
            <unit mrp="os/buildtools/toolsandutils/statsource/group/testtools_stat_common_source.mrp"/>
          </component>
          <component name="wintunnel" long-name="Wintunnel" purpose="development">
            <unit mrp="os/buildtools/toolsandutils/wintunnel/group/testtools_WinTunnel_srconly.mrp"/>
          </component>
          <component name="autotest" long-name="Autotest" purpose="development">
            <unit bldFile="os/buildtools/toolsandutils/autotest/group" mrp="os/buildtools/toolsandutils/autotest/group/tools_autotest.mrp"/>
          </component>
          <component name="kitsetupapp" long-name="Kit Setup App" filter="gt" purpose="development">
            <unit mrp="os/buildtools/toolsandutils/kitsetupapp/group/tools_devkits_kitsetupapp.mrp"/>
          </component>
          <component name="navigationpages" long-name="Navigation Pages" purpose="development">
            <unit mrp="os/buildtools/toolsandutils/navigationpages/tools_sdk_eng_NavigationPages.mrp"/>
          </component>
        </collection>
        <collection name="sbsv1_os" long-name="Symbian Build System v1" level="fw">
          <component name="e32toolp" long-name="E32 Perl Tools" purpose="development" class="PC">
            <unit mrp="os/buildtools/sbsv1_os/e32toolp/group/tools_e32toolp.mrp"/>
          </component>
        </collection>
        <collection name="imgtools_os" long-name="Image Tools" level="fw">
          <component name="romkiteka2" long-name="ROMKIT EKA2" deprecated="tb91" purpose="development">
            <unit bldFile="os/buildtools/imgtools_os/romkiteka2/group" mrp="os/buildtools/imgtools_os/romkiteka2/group/tools_romkit.mrp"/>
          </component>
        </collection>
        <collection name="devlib" long-name="Developer Library" level="ui">
          <component name="Developer Library HTML">
           <unit mrp="os/buildtools/devlib/devlibhelp/group/shared/developerlibrary_doc_plain_html.mrp"/>
          </component>
          <component name="toolsdocs" long-name="Tools Documentation" purpose="development" class="doc">
            <unit mrp="os/buildtools/devlib/toolsdocs/tools_documentation.mrp"/>
          </component>
        </collection>
        <collection name="misccomponents" long-name="Misc Components" level="mw">
          <component name="emulatorlauncher" long-name="Emulator Launcher" filter="gt" purpose="development">
            <unit bldFile="os/buildtools/misccomponents/emulatorlauncher/group" mrp="os/buildtools/misccomponents/emulatorlauncher/group/tools_sdk_eng_emulator_launcher.mrp"/>
          </component>
        </collection>
      </block>
      <block name="ossrv" level="services" long-name="Generic OS Services" levels="physical-abstraction app-libs encoding translation data-services utilities">
        <collection name="genericservices" long-name="Generic Services" level="utilities">
          <component name="s60compatibilityheaders" long-name="S60 Compatibility Headers" filter="gt" purpose="development">
            <unit bldFile="os/ossrv/genericservices/s60compatibilityheaders/group94" mrp="os/ossrv/genericservices/s60compatibilityheaders/group94/tools_s60_header_compat94.mrp" version="9.4"/>
          </component>
          <component name="mimerecognitionfw" long-name="MIME Recognition Framework" purpose="mandatory">
            <unit bldFile="os/ossrv/genericservices/mimerecognitionfw/group" mrp="os/ossrv/genericservices/mimerecognitionfw/group/app-framework_emime.mrp"/>
          </component>
          <component name="systemagent" long-name="System Agent" introduced="9.0" purpose="mandatory">
            <unit bldFile="os/ossrv/genericservices/systemagent/group" mrp="os/ossrv/genericservices/systemagent/group/syslibs_sysagent2.mrp"/>
          </component>
          <component name="taskscheduler" long-name="Task Scheduler" introduced="6.0" purpose="optional">
            <unit bldFile="os/ossrv/genericservices/taskscheduler/group" mrp="os/ossrv/genericservices/taskscheduler/group/syslibs_schsvr.mrp"/>
          </component>
          <component name="activebackupclient" long-name="Active Backup Client" purpose="optional">
            <unit bldFile="os/ossrv/genericservices/activebackupclient/group" mrp="os/ossrv/genericservices/activebackupclient/group/connectivity_abclient.mrp"/>
          </component>
          <component name="syslibsdocs" long-name="Syslibs Documentation" purpose="development" class="doc">
            <unit mrp="os/ossrv/genericservices/syslibsdocs/syslibs_documentation.mrp"/>
          </component>
          <component name="httputils" long-name="HTTP Utilities Library" introduced="6.2" purpose="optional">
            <unit bldFile="os/ossrv/genericservices/httputils/group" mrp="os/ossrv/genericservices/httputils/group/application-protocols_inetprotutil.mrp"/>
          </component>
        </collection>
        <collection name="genericopenlibs" long-name="Generic Open Libraries" level="translation">
          <component name="openenvcore" long-name="Open Environment Core" introduced="tb91" purpose="mandatory">
            <unit bldFile="os/ossrv/genericopenlibs/openenvcore/group" mrp="os/ossrv/genericopenlibs/openenvcore/group/openenv.mrp"/>
          </component>
        </collection>
        <collection name="lowlevellibsandfws" long-name="Low Level Libraries and Frameworks" level="app-libs">
          <component name="pluginfw" long-name="Plugin Framework" introduced="6.2" purpose="mandatory">
            <unit bldFile="os/ossrv/lowlevellibsandfws/pluginfw/Group" mrp="os/ossrv/lowlevellibsandfws/pluginfw/Group/syslibs_ecom.mrp" version="2"/>
          </component>
          <component name="apputils" long-name="Application Utilities" introduced="ER5" purpose="mandatory">
            <unit bldFile="os/ossrv/lowlevellibsandfws/apputils/group" mrp="os/ossrv/lowlevellibsandfws/apputils/group/syslibs_bafl.mrp"/>
          </component>
        </collection>
      </block>
      <block name="security" level="services" long-name="OS Security" levels="physical-abstraction plugins libraries management services utilities">
        <collection name="contentmgmt" long-name="Content Management" level="utilities">
          <component name="contentaccessfwfordrm" long-name="Content Access Framework for DRM" introduced="9.1" purpose="mandatory">
            <unit bldFile="os/security/contentmgmt/contentaccessfwfordrm/group" mrp="os/security/contentmgmt/contentaccessfwfordrm/group/security_caf2.mrp"/>
          </component>
        </collection>
        <collection name="crypto" long-name="Crypto Libraries" level="libraries">
          <component name="strongcrypto" long-name="Strong Cryptography Library" filter="gt" purpose="optional">
            <unit bldFile="os/security/crypto/weakcrypto/strong" mrp="os/security/crypto/weakcrypto/group/security_crypto_strong.mrp"/>
          </component>
        </collection>
        <collection name="cryptomgmtlibs" long-name="Crypto Management Libraries" level="management">
          <component name="securityutils" long-name="Security Utils" introduced="8.0" purpose="optional">
            <unit bldFile="os/security/cryptomgmtlibs/securityutils/group" mrp="os/security/cryptomgmtlibs/securityutils/group/security_common.mrp"/>
          </component>
          <component name="securitytestfw" long-name="Security Test Framework" introduced="7.0" deprecated="tb92" purpose="development">
            <unit mrp="os/security/cryptomgmtlibs/securitytestfw/group/security_testframework.mrp"/>
          </component>
          <component name="securitydocs" long-name="Security Documentation" purpose="development" class="doc">
            <unit mrp="os/security/cryptomgmtlibs/securitydocs/security_documentation.mrp"/>
          </component>
          <component name="cryptotokenfw" long-name="Crypto Token Framework" introduced="7.0" purpose="optional">
            <unit bldFile="os/security/cryptomgmtlibs/cryptotokenfw/group" mrp="os/security/cryptomgmtlibs/cryptotokenfw/group/security_cryptotokens.mrp"/>
          </component>
        </collection>
        <collection name="securityanddataprivacytools" long-name="Security and Data Privacy Tools" level="services">
          <component name="securityconfig" long-name="Security Config" introduced="9.1" purpose="optional">
            <unit bldFile="os/security/securityanddataprivacytools/securityconfig/group" mrp="os/security/securityanddataprivacytools/securityconfig/group/security_config.mrp"/>
          </component>
          <component name="securitytools" long-name="Security Tools" introduced="tb92" purpose="optional" class="PC">
            <unit bldFile="os/security/securityanddataprivacytools/securitytools/group" mrp="os/security/securityanddataprivacytools/securitytools/group/security_tools.mrp"/>
          </component>
        </collection>
        <collection name="cryptoservices" long-name="Crypto Services" level="plugins">
          <component name="certificateandkeymgmt" long-name="Certificate and Key Management" introduced="6.0" purpose="optional">
            <unit bldFile="os/security/cryptoservices/certificateandkeymgmt/group" mrp="os/security/cryptoservices/certificateandkeymgmt/group/security_certman.mrp"/>
          </component>
          <component name="filebasedcertificateandkeystores" long-name="File-based Certificate and Key Stores" introduced="8.0" purpose="optional">
            <unit bldFile="os/security/cryptoservices/filebasedcertificateandkeystores/group" mrp="os/security/cryptoservices/filebasedcertificateandkeystores/group/security_filetokens.mrp"/>
          </component>
          <component name="rootcertificates" long-name="Root Certificates" introduced="7.0s" purpose="optional">
            <unit mrp="os/security/cryptoservices/rootcertificates/rootcerts.mrp"/>
          </component>
          <component name="asnpkcs" long-name="ASN PKCS" introduced="8.0" purpose="optional">
            <unit bldFile="os/security/cryptoservices/asnpkcs/group" mrp="os/security/cryptoservices/asnpkcs/group/security_asnpkcs.mrp"/>
          </component>
        </collection>
      </block>
      <block name="persistentdata" level="services" long-name="Persistent Data Services" levels="adaptation hw-if plugin framework server app-if">
        <collection name="featuremgmt" long-name="Feature Management" level="framework">
          <component name="featureregistry" long-name="Feature Registry" introduced="9.2" deprecated="tb92" purpose="mandatory">
            <unit bldFile="os/persistentdata/featuremgmt/featureregistry/group" mrp="os/persistentdata/featuremgmt/featureregistry/group/syslibs_featreg.mrp"/>
          </component>
        </collection>
        <collection name="loggingservices" long-name="Logging Services" level="server">
          <component name="eventlogger" long-name="Event Logger" introduced="6.0" purpose="optional">
            <unit bldFile="os/persistentdata/loggingservices/eventlogger/group" mrp="os/persistentdata/loggingservices/eventlogger/group/syslibs_logeng.mrp"/>
          </component>
          <component name="filelogger" long-name="File Logger" introduced="ER5" purpose="optional">
            <unit bldFile="os/persistentdata/loggingservices/filelogger/group" mrp="os/persistentdata/loggingservices/filelogger/group/comms-infras_flogger.mrp"/>
          </component>
          <component name="rfilelogger" long-name="RFile Logger" deprecated="tb92" introduced="9.1" purpose="development">
            <unit bldFile="os/persistentdata/loggingservices/rfilelogger/group" mrp="os/persistentdata/loggingservices/rfilelogger/group/testtools_utilities.mrp"/>
          </component>
        </collection>
        <collection name="traceservices" long-name="Trace Services" level="server">
          <component name="commsdebugutility" long-name="Comms Debug Utility" introduced="7.0s" purpose="optional">
            <unit bldFile="os/persistentdata/traceservices/commsdebugutility/group" mrp="os/persistentdata/traceservices/commsdebugutility/group/comms-infras_commsdebugutility.mrp"/>
          </component>
          <component name="tracefw" long-name="Trace Framework" introduced="9.2" purpose="development">
            <unit bldFile="os/persistentdata/traceservices/tracefw/ulogger/group" mrp="os/persistentdata/traceservices/tracefw/ulogger/group/tools_debug_trace.mrp"/>
          </component>
          <component name="utrace" long-name="UTrace" introduced="9.3" deprecated="tb91" purpose="development">
            <unit bldFile="os/persistentdata/traceservices/utrace/group" mrp="os/persistentdata/traceservices/utrace/group/testtools_utrace_api.mrp"/>
          </component>
        </collection>
        <collection name="persistentstorage" long-name="Persistent Storage" level="framework">
          <component name="store" long-name="Store" purpose="optional">
            <unit bldFile="os/persistentdata/persistentstorage/store/group" mrp="os/persistentdata/persistentstorage/store/group/syslibs_store.mrp"/>
          </component>
          <component name="dbms" long-name="DBMS" purpose="optional">
            <unit bldFile="os/persistentdata/persistentstorage/dbms/group" mrp="os/persistentdata/persistentstorage/dbms/group/syslibs_dbms.mrp"/>
          </component>
          <component name="centralrepository" long-name="Central Repository" introduced="7.0s" purpose="mandatory">
            <unit bldFile="os/persistentdata/persistentstorage/centralrepository/group" mrp="os/persistentdata/persistentstorage/centralrepository/group/syslibs_centralrepository.mrp"/>
          </component>
          <component name="sql" long-name="SQL" introduced="9.3" purpose="optional">
            <unit bldFile="os/persistentdata/persistentstorage/sql/GROUP" mrp="os/persistentdata/persistentstorage/sql/GROUP/syslibs_sql.mrp"/>
          </component>
        </collection>
      </block>
      <block name="devicesrv" level="services" long-name="Device Services" levels="adaptation hw-if plugin framework server app-if">
        <collection name="accessoryservices" long-name="Accessory Services" level="framework">
          <component name="remotecontrolfw" long-name="Remote Control Framework" introduced="9.1" purpose="optional">
            <unit bldFile="os/devicesrv/accessoryservices/remotecontrolfw/group" mrp="os/devicesrv/accessoryservices/remotecontrolfw/group/bluetooth_remotecontrol.mrp"/>
          </component>
        </collection>
        <collection name="resourcemgmt" long-name="Resource Management" level="hw-if">
          <component name="hwresourcesmgr" long-name="Hardware Resources Manager" introduced="tb91" purpose="optional">
            <unit bldFile="os/devicesrv/resourcemgmt/hwresourcesmgr/group" mrp="os/devicesrv/resourcemgmt/hwresourcesmgr/group/telephony_hwrm.mrp"/>
          </component>
          <component name="powerandmemorynotificationservice" long-name="Power and Memory Notification Service" introduced="6.0" purpose="mandatory">
            <unit bldFile="os/devicesrv/resourcemgmt/powerandmemorynotificationservice/group" mrp="os/devicesrv/resourcemgmt/powerandmemorynotificationservice/group/syslibs_pwrcli.mrp"/>
          </component>
        </collection>
        <collection name="sysstatemgmt" long-name="System State Management" level="server">
          <component name="systemstarter" long-name="System Starter" introduced="9.1" deprecated="tb92" purpose="mandatory">
            <unit bldFile="os/devicesrv/sysstatemgmt/systemstarter/group" mrp="os/devicesrv/sysstatemgmt/systemstarter/group/app-framework_sysstart.mrp"/>
          </component>
        </collection>
      </block>
      <block name="lbs" level="services" long-name="Locating Services" levels="hw-if data-acquisition adaptation management application-interface">
        <collection name="datasourcemodules" long-name="Generic Positioning Plugins" level="data-acquisition">